package wildlog.ui.dialogs;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.Element;
import wildlog.data.dataobjects.Location;
import wildlog.data.dataobjects.Sighting;
import wildlog.data.dataobjects.Visit;
import wildlog.data.dataobjects.WildLogFile;
import wildlog.html.utils.UtilsHTML;
import wildlog.mapping.kml.utils.UtilsKML;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.helpers.ProgressbarTask;
import wildlog.ui.utils.UtilsTime;
import wildlog.utils.UtilsConcurency;
import wildlog.utils.UtilsFileProcessing;
import wildlog.utils.WildLogPaths;
import wildlog.xml.utils.UtilsXML;


public class ExportDialog extends JDialog {
    private final WildLogApp app;
    private final Location location;
    private final Element element;
    private final Visit visit;
    private final Sighting sighting;
    private List<Sighting> lstSightings;

    
    public ExportDialog(WildLogApp inApp, Location inLocation, Element inElement, Visit inVisit, Sighting inSighting, List<Sighting> inLstSightings) {
        super(inApp.getMainFrame());
        System.out.println("[ExportDialog]");
        // Set passed in values
        app = inApp;
        location = inLocation;
        element = inElement;
        visit = inVisit;
        sighting = inSighting;
        lstSightings = inLstSightings;
        // Auto generated code
        initComponents();
        // Determine what buttons to show
        if (element == null && location == null && visit == null) {
            btnExportFiles.setVisible(false);
            btnExportFilesObservations.setVisible(false);
        }
        if (inLstSightings == null || inLstSightings.isEmpty()) {
            btnExportFilesSelectedObservations.setVisible(false);
        }
        // Pack
        pack();
        // Setup the default behavior
        UtilsDialog.addEscapeKeyListener(this);
        UtilsDialog.setDialogToCenter(app.getMainFrame(), this);
        UtilsDialog.addModalBackgroundPanel(app.getMainFrame(), this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportFiles = new javax.swing.JButton();
        btnExportFilesObservations = new javax.swing.JButton();
        btnExportFilesSelectedObservations = new javax.swing.JButton();
        btnExportWorkspace = new javax.swing.JButton();
        btnExportHTML = new javax.swing.JButton();
        btnExportHTMLAdvanced = new javax.swing.JButton();
        btnExportCSVBasic = new javax.swing.JButton();
        btnExportCSV = new javax.swing.JButton();
        btnExportXML = new javax.swing.JButton();
        btnExportKML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Available Exports");
        setIconImage(new ImageIcon(app.getClass().getResource("resources/icons/Export.png")).getImage());
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        btnExportFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/File.png"))); // NOI18N
        btnExportFiles.setText("Export Files");
        btnExportFiles.setToolTipText("Save copies of all relevant files in the Export folder.");
        btnExportFiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportFiles.setFocusPainted(false);
        btnExportFiles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportFiles.setIconTextGap(10);
        btnExportFiles.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportFiles.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportFiles.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportFiles.setName("btnExportFiles"); // NOI18N
        btnExportFiles.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFilesActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportFiles);

        btnExportFilesObservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/File.png"))); // NOI18N
        btnExportFilesObservations.setText("Export Files for all the Observations");
        btnExportFilesObservations.setToolTipText("Save copies of all relevant files in the Export folder.");
        btnExportFilesObservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportFilesObservations.setFocusPainted(false);
        btnExportFilesObservations.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportFilesObservations.setIconTextGap(10);
        btnExportFilesObservations.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportFilesObservations.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportFilesObservations.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportFilesObservations.setName("btnExportFilesObservations"); // NOI18N
        btnExportFilesObservations.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportFilesObservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFilesObservationsActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportFilesObservations);

        btnExportFilesSelectedObservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/File.png"))); // NOI18N
        btnExportFilesSelectedObservations.setText("Export Files for the selected Observations");
        btnExportFilesSelectedObservations.setToolTipText("Save copies of the selected Observations' files in the Export folder.");
        btnExportFilesSelectedObservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportFilesSelectedObservations.setFocusPainted(false);
        btnExportFilesSelectedObservations.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportFilesSelectedObservations.setIconTextGap(10);
        btnExportFilesSelectedObservations.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportFilesSelectedObservations.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportFilesSelectedObservations.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportFilesSelectedObservations.setName("btnExportFilesSelectedObservations"); // NOI18N
        btnExportFilesSelectedObservations.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportFilesSelectedObservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFilesSelectedObservationsActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportFilesSelectedObservations);

        btnExportWorkspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/WildLog Icon.gif"))); // NOI18N
        btnExportWorkspace.setText("Export to New Workspace");
        btnExportWorkspace.setToolTipText("Create a new Workspace containing only relevant data and linked records.");
        btnExportWorkspace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportWorkspace.setFocusPainted(false);
        btnExportWorkspace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportWorkspace.setIconTextGap(10);
        btnExportWorkspace.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportWorkspace.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportWorkspace.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportWorkspace.setName("btnExportWorkspace"); // NOI18N
        btnExportWorkspace.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportWorkspaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportWorkspace);

        btnExportHTML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/HTML Icon.gif"))); // NOI18N
        btnExportHTML.setText("Export as Offline Webpage (Basic)");
        btnExportHTML.setToolTipText("Create a HTML web page for all relevant Observations and linked records. Can be viewed in a web browser.");
        btnExportHTML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportHTML.setFocusPainted(false);
        btnExportHTML.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportHTML.setIconTextGap(10);
        btnExportHTML.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportHTML.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportHTML.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportHTML.setName("btnExportHTML"); // NOI18N
        btnExportHTML.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportHTMLActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportHTML);

        btnExportHTMLAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/HTML Icon.gif"))); // NOI18N
        btnExportHTMLAdvanced.setText("Export as Webpage (Advanced)");
        btnExportHTMLAdvanced.setToolTipText("Create a HTML web page for all relevant Observations and linked records. Can be viewed in a web browser.");
        btnExportHTMLAdvanced.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportHTMLAdvanced.setEnabled(false);
        btnExportHTMLAdvanced.setFocusPainted(false);
        btnExportHTMLAdvanced.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportHTMLAdvanced.setIconTextGap(10);
        btnExportHTMLAdvanced.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportHTMLAdvanced.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportHTMLAdvanced.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportHTMLAdvanced.setName("btnExportHTMLAdvanced"); // NOI18N
        btnExportHTMLAdvanced.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportHTMLAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportHTMLAdvancedActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportHTMLAdvanced);

        btnExportCSVBasic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/CSV.png"))); // NOI18N
        btnExportCSVBasic.setText("Export as Spreadsheet (Basic)");
        btnExportCSVBasic.setToolTipText("Export a CSV file for all relevant Observations. Can be opened in Excel, etc.");
        btnExportCSVBasic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportCSVBasic.setFocusPainted(false);
        btnExportCSVBasic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportCSVBasic.setIconTextGap(10);
        btnExportCSVBasic.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportCSVBasic.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportCSVBasic.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportCSVBasic.setName("btnExportCSVBasic"); // NOI18N
        btnExportCSVBasic.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportCSVBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCSVBasicActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportCSVBasic);

        btnExportCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/CSV.png"))); // NOI18N
        btnExportCSV.setText("Export as Spreadsheet (Complete)");
        btnExportCSV.setToolTipText("Export a CSV file for all relevant Observations and linked records. Can be opened in Excel, etc.");
        btnExportCSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportCSV.setFocusPainted(false);
        btnExportCSV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportCSV.setIconTextGap(10);
        btnExportCSV.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportCSV.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportCSV.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportCSV.setName("btnExportCSV"); // NOI18N
        btnExportCSV.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCSVActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportCSV);

        btnExportXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/XML.png"))); // NOI18N
        btnExportXML.setText("Export as XML");
        btnExportXML.setToolTipText("Export a XML file for all relevant Observations and linked records.");
        btnExportXML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportXML.setFocusPainted(false);
        btnExportXML.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportXML.setIconTextGap(10);
        btnExportXML.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportXML.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportXML.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportXML.setName("btnExportXML"); // NOI18N
        btnExportXML.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportXMLActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportXML);

        btnExportKML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/GoogleEarth.png"))); // NOI18N
        btnExportKML.setText("Export as KML");
        btnExportKML.setToolTipText("Export a KML file for all relevant Observations and linked records. Can be opened in Google Earth, etc.");
        btnExportKML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportKML.setFocusPainted(false);
        btnExportKML.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportKML.setIconTextGap(11);
        btnExportKML.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnExportKML.setMaximumSize(new java.awt.Dimension(260, 35));
        btnExportKML.setMinimumSize(new java.awt.Dimension(260, 35));
        btnExportKML.setName("btnExportKML"); // NOI18N
        btnExportKML.setPreferredSize(new java.awt.Dimension(260, 35));
        btnExportKML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportKMLActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportKML);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportHTMLActionPerformed
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsHTML.exportHTML(element, app, this));
                    return null;
                }
            });
        }
        if (location != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsHTML.exportHTML(location, app, this));
                    return null;
                }
            });
        }
        if (visit != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsHTML.exportHTML(visit, app, this));
                    return null;
                }
            });
        }
        if (sighting != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsHTML.exportHTML(sighting, app, this));
                    return null;
                }
            });
        }
        if (lstSightings != null && !lstSightings.isEmpty()) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Starting the HTML Export for Observations");
                    for (Sighting tempSighting : lstSightings) {
                        UtilsHTML.exportHTML(tempSighting, app, this);
                    }
                    setProgress(100);
                    setMessage("Done with the HTML Export for Observations");
                    UtilsFileProcessing.openFile(WildLogPaths.WILDLOG_EXPORT_HTML.getAbsoluteFullPath());
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportHTMLActionPerformed

    private void btnExportFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFilesActionPerformed
        // Copy the files to the export folder and open the folder
        if (location != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Files for '" + location.getName() + "'");
                    List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(location.getWildLogFileID()));
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Location.WILDLOG_FOLDER_PREFIX)
                            .resolve(location.getName());
                    Files.createDirectories(destination);
                    setProgress(1);
                    setMessage("Exporting Files for '" + location.getName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (WildLogFile wildLogFile : listFiles) {
                        UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), destination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        setProgress(1 + (int)(counter/(double)listFiles.size()*98));
                        setMessage("Exporting Files for '" + location.getName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Files for '" + location.getName() + "'");
                    return null;
                }
            });
        }
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Files for '" + element.getPrimaryName() + "'");
                    List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(element.getWildLogFileID()));
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Element.WILDLOG_FOLDER_PREFIX)
                            .resolve(element.getPrimaryName());
                    Files.createDirectories(destination);
                    setProgress(1);
                    setMessage("Exporting Files for '" + element.getPrimaryName()+ "' " + getProgress() + "%");
                    int counter = 0;
                    for (WildLogFile wildLogFile : listFiles) {
                        UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), destination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        setProgress(1 + (int)(counter/(double)listFiles.size()*98));
                        setMessage("Exporting Files for '" + element.getPrimaryName()+ "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Files for '" + element.getPrimaryName() + "'");
                    return null;
                }
            });
        }
        if (visit != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                   setProgress(0);
                    setMessage("Exporting Files for '" + visit.getName() + "'");
                    List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(visit.getWildLogFileID()));
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Visit.WILDLOG_FOLDER_PREFIX)
                            .resolve(visit.getName());
                    Files.createDirectories(destination);
                    setProgress(1);
                    setMessage("Exporting Files for '" + visit.getName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (WildLogFile wildLogFile : listFiles) {
                        UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), destination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        setProgress(1 + (int)(counter/(double)listFiles.size()*98));
                        setMessage("Exporting Files for '" + visit.getName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Files for '" + visit.getName() + "'");
                    return null;
                }
            });
        }
        if (sighting != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Files for '" + sighting.getDisplayName() + "'");
                    List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(sighting.getWildLogFileID()));
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                            .resolve(sighting.getDisplayName());
                    Files.createDirectories(destination);
                    setProgress(1);
                    setMessage("Exporting Files for '" + sighting.getDisplayName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (WildLogFile wildLogFile : listFiles) {
                        UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), destination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        setProgress(1 + (int)(counter/(double)listFiles.size()*98));
                        setMessage("Exporting Files for '" + sighting.getDisplayName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Files for '" + sighting.getDisplayName() + "'");
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportFilesActionPerformed

    private void btnExportWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportWorkspaceActionPerformed
        Path destinationRoot;
        if (element != null) {
            destinationRoot = WildLogPaths.WILDLOG_EXPORT_WORKSPACE.getAbsoluteFullPath()
                    .resolve(Element.WILDLOG_FOLDER_PREFIX)
                    .resolve(element.getDisplayName())
                    .resolve(UtilsTime.WL_DATE_FORMATTER_FOR_FILES_WITH_TIMESTAMP.format(LocalDateTime.now()));
            lstSightings = app.getDBI().list(new Sighting(element.getPrimaryName(), null, null), false);
        }
        else
        if (location != null) {
            destinationRoot = WildLogPaths.WILDLOG_EXPORT_WORKSPACE.getAbsoluteFullPath()
                    .resolve(Location.WILDLOG_FOLDER_PREFIX)
                    .resolve(location.getDisplayName())
                    .resolve(UtilsTime.WL_DATE_FORMATTER_FOR_FILES_WITH_TIMESTAMP.format(LocalDateTime.now()));
            lstSightings = app.getDBI().list(new Sighting(null, location.getName(), null), false);
        }
        else
        if (visit != null) {
            destinationRoot = WildLogPaths.WILDLOG_EXPORT_WORKSPACE.getAbsoluteFullPath()
                    .resolve(Visit.WILDLOG_FOLDER_PREFIX)
                    .resolve(visit.getDisplayName())
                    .resolve(UtilsTime.WL_DATE_FORMATTER_FOR_FILES_WITH_TIMESTAMP.format(LocalDateTime.now()));
            lstSightings = app.getDBI().list(new Sighting(null, null, visit.getName()), false);
        }
        else
        if (sighting != null) {
            destinationRoot = WildLogPaths.WILDLOG_EXPORT_WORKSPACE.getAbsoluteFullPath()
                    .resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                    .resolve(sighting.getDisplayName())
                    .resolve(UtilsTime.WL_DATE_FORMATTER_FOR_FILES_WITH_TIMESTAMP.format(LocalDateTime.now()));
            lstSightings = app.getDBI().list(sighting, false);
        }
        else
        if (lstSightings != null && !lstSightings.isEmpty()) {
            destinationRoot = WildLogPaths.WILDLOG_EXPORT_WORKSPACE.getAbsoluteFullPath()
                    .resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                    .resolve("Observations")
                    .resolve(UtilsTime.WL_DATE_FORMATTER_FOR_FILES_WITH_TIMESTAMP.format(LocalDateTime.now()));
        }
        else {
            destinationRoot = null;
        }
        // Hide this dialog
        setVisible(false);
        dispose();
        // Show the Workspace export dialog
        if (destinationRoot != null && lstSightings != null && !lstSightings.isEmpty()) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    WorkspaceExportDialog dialog = new WorkspaceExportDialog(app, destinationRoot, lstSightings);
                    dialog.setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_btnExportWorkspaceActionPerformed

    private void btnExportKMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportKMLActionPerformed
        if (location != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsKML.exportKML(location, this, app, true);
                    return null;
                }
            });
        }
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsKML.exportKML(element, this, app, true);
                    return null;
                }
            });
        }
        if (visit != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsKML.exportKML(visit, this, app, true);
                    return null;
                }
            });
        }
        if (sighting != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsKML.exportKML(sighting, this, app, true);
                    return null;
                }
            });
        }
        if (lstSightings != null && !lstSightings.isEmpty()) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Starting the KML Export for Observations");
                    for (Sighting tempSighting : lstSightings) {
                        UtilsKML.exportKML(tempSighting, this, app, false);
                    }
                    setProgress(100);
                    setMessage("Done with the KML Export for Observations");
                    UtilsFileProcessing.openFile(WildLogPaths.WILDLOG_EXPORT_KML.getAbsoluteFullPath());
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportKMLActionPerformed

    private void btnExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCSVActionPerformed
        UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
            @Override
            protected Object doInBackground() throws Exception {
                setMessage("Starting the CSV Export");
                Path path;
                if (location != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath().resolve(Location.WILDLOG_FOLDER_PREFIX)
                            .resolve(location.getDisplayName());
                }
                else
                if (visit != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath().resolve(Visit.WILDLOG_FOLDER_PREFIX)
                            .resolve(visit.getDisplayName());
                }
                else
                if (element != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath().resolve(Element.WILDLOG_FOLDER_PREFIX)
                            .resolve(element.getDisplayName());
                }
                else
                if (sighting != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath().resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                            .resolve(sighting.getDisplayName());
                }
                else
                if (lstSightings != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath().resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                            .resolve("Observations");
                }
                else {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV.getAbsoluteFullPath();
                }
                Files.createDirectories(path);
                app.getDBI().doExportCSV(path, false, location, visit, element, sighting, lstSightings);
                UtilsFileProcessing.openFile(path);
                setMessage("Done with the CSV Export");
                return null;
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportCSVActionPerformed

    private void btnExportFilesObservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFilesObservationsActionPerformed
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Observation Files for '" + element.getDisplayName() + "'");
                    List<Sighting> listSightings = app.getDBI().list(new Sighting(element.getPrimaryName(), null, null), false);
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Element.WILDLOG_FOLDER_PREFIX)
                            .resolve(element.getDisplayName()).resolve(Sighting.WILDLOG_FOLDER_PREFIX);
                    setProgress(1);
                    setMessage("Exporting Observation Files for '" + element.getDisplayName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (Sighting exportSighting : listSightings) {
                        List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(exportSighting.getWildLogFileID()));
                        Path exportDestination = destination.resolve(exportSighting.getDisplayName());
                        Files.createDirectories(exportDestination);
                        for (WildLogFile wildLogFile : listFiles) {
                            UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), exportDestination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        }
                        setProgress(1 + (int)(counter/(double)listSightings.size()*98));
                        setMessage("Exporting Observation Files for '" + element.getDisplayName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Observation Files for '" + element.getDisplayName() + "'");
                    return null;
                }
            });
        }
        if (location != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Observation Files for '" + location.getDisplayName() + "'");
                    List<Sighting> listSightings = app.getDBI().list(new Sighting(null, location.getName(), null), false);
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Location.WILDLOG_FOLDER_PREFIX)
                            .resolve(location.getDisplayName()).resolve(Sighting.WILDLOG_FOLDER_PREFIX);
                    setProgress(1);
                    setMessage("Exporting Observation Files for '" + location.getDisplayName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (Sighting exportSighting : listSightings) {
                        List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(exportSighting.getWildLogFileID()));
                        Path exportDestination = destination.resolve(exportSighting.getDisplayName());
                        Files.createDirectories(exportDestination);
                        for (WildLogFile wildLogFile : listFiles) {
                            UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), exportDestination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        }
                        setProgress(1 + (int)(counter/(double)listSightings.size()*98));
                        setMessage("Exporting Observation Files for '" + location.getDisplayName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Observation Files for '" + location.getDisplayName() + "'");
                    return null;
                }
            });
        }
        if (visit != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Observation Files for '" + visit.getDisplayName() + "'");
                    List<Sighting> listSightings = app.getDBI().list(new Sighting(null, null, visit.getName()), false);
                    Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                            .resolve(Visit.WILDLOG_FOLDER_PREFIX)
                            .resolve(visit.getDisplayName()).resolve(Sighting.WILDLOG_FOLDER_PREFIX);
                    setProgress(1);
                    setMessage("Exporting Observation Files for '" + visit.getDisplayName() + "' " + getProgress() + "%");
                    int counter = 0;
                    for (Sighting exportSighting : listSightings) {
                        List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(exportSighting.getWildLogFileID()));
                        Path exportDestination = destination.resolve(exportSighting.getDisplayName());
                        Files.createDirectories(exportDestination);
                        for (WildLogFile wildLogFile : listFiles) {
                            UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), exportDestination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                        }
                        setProgress(1 + (int)(counter/(double)listSightings.size()*98));
                        setMessage("Exporting Observation Files for '" + visit.getDisplayName() + "' " + getProgress() + "%");
                        counter++;
                    }
                    UtilsFileProcessing.openFile(destination);
                    setProgress(100);
                    setMessage("Done Exporting Observation Files for '" + visit.getDisplayName() + "'");
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportFilesObservationsActionPerformed

    private void btnExportHTMLAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportHTMLAdvancedActionPerformed
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsHTML.copyFancyHtmlResources(WildLogPaths.WILDLOG_EXPORT_HTML_FANCY_RESOURCES.getAbsoluteFullPath());
                    UtilsFileProcessing.openFile(UtilsHTML.exportFancyHTML(element, app, this));
                    return null;
                }
            });
        }
// TODO: Generate fancy HTML
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportHTMLAdvancedActionPerformed

    private void btnExportCSVBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCSVBasicActionPerformed
        UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
            @Override
            protected Object doInBackground() throws Exception {
                setMessage("Starting the Basic CSV Export");
                Path path;
                if (location != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath().resolve(Location.WILDLOG_FOLDER_PREFIX)
                            .resolve(location.getDisplayName());
                }
                else
                if (visit != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath().resolve(Visit.WILDLOG_FOLDER_PREFIX)
                            .resolve(visit.getDisplayName());
                }
                else
                if (element != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath().resolve(Element.WILDLOG_FOLDER_PREFIX)
                            .resolve(element.getDisplayName());
                }
                else
                if (sighting != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath().resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                            .resolve(sighting.getDisplayName());
                }
                else
                if (lstSightings != null) {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath().resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                            .resolve("Observations");
                }
                else {
                    path = WildLogPaths.WILDLOG_EXPORT_CSV_BASIC.getAbsoluteFullPath();
                }
                Files.createDirectories(path);
                app.getDBI().doExportBasicCSV(path, location, visit, element, sighting, lstSightings);
                UtilsFileProcessing.openFile(path);
                setMessage("Done with the Basic CSV Export");
                return null;
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportCSVBasicActionPerformed

    private void btnExportXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportXMLActionPerformed
        if (element != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsXML.exportXML(element, app, this, true));
                    return null;
                }
            });
        }
        if (location != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsXML.exportXML(location, app, this, true));
                    return null;
                }
            });
        }
        if (visit != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsXML.exportXML(visit, app, this, true));
                    return null;
                }
            });
        }
        if (sighting != null) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    UtilsFileProcessing.openFile(UtilsXML.exportXML(sighting, app, this, true));
                    return null;
                }
            });
        }
        if (lstSightings != null && !lstSightings.isEmpty()) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Starting the XML Export for Observations");
                    for (Sighting tempSighting : lstSightings) {
                        UtilsXML.exportXML(tempSighting, app, this, true);
                    }
                    setProgress(100);
                    setMessage("Done with the XML Export for Observations");
                    UtilsFileProcessing.openFile(WildLogPaths.WILDLOG_EXPORT_XML.getAbsoluteFullPath());
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportXMLActionPerformed

    private void btnExportFilesSelectedObservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFilesSelectedObservationsActionPerformed
        if (lstSightings != null && !lstSightings.isEmpty()) {
            UtilsConcurency.kickoffProgressbarTask(app, new ProgressbarTask(app) {
                @Override
                protected Object doInBackground() throws Exception {
                    setProgress(0);
                    setMessage("Exporting Files for Observations");
                    for (Sighting tempSighting : lstSightings) {
                        setProgress(0);
                        setMessage("Exporting Files for '" + tempSighting.getDisplayName() + "'");
                        List<WildLogFile> listFiles = app.getDBI().list(new WildLogFile(tempSighting.getWildLogFileID()));
                        Path destination = WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath()
                                .resolve(Sighting.WILDLOG_FOLDER_PREFIX)
                                .resolve(tempSighting.getDisplayName());
                        Files.createDirectories(destination);
                        setProgress(1);
                        setMessage("Exporting Files for '" + tempSighting.getDisplayName() + "' " + getProgress() + "%");
                        int counter = 0;
                        for (WildLogFile wildLogFile : listFiles) {
                            UtilsFileProcessing.copyFile(wildLogFile.getAbsolutePath(), destination.resolve(wildLogFile.getRelativePath().getFileName()), true, true);
                            setProgress(1 + (int)(counter/(double)listFiles.size()*98));
                            setMessage("Exporting Files for '" + tempSighting.getDisplayName() + "' " + getProgress() + "%");
                            counter++;
                        }
                        setProgress(100);
                        setMessage("Done Exporting Files for '" + tempSighting.getDisplayName() + "'");
                    }
                    setProgress(100);
                    setMessage("Done Exporting Files for Observations");
                    UtilsFileProcessing.openFile(WildLogPaths.WILDLOG_EXPORT_FILES.getAbsoluteFullPath());
                    return null;
                }
            });
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExportFilesSelectedObservationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JButton btnExportCSVBasic;
    private javax.swing.JButton btnExportFiles;
    private javax.swing.JButton btnExportFilesObservations;
    private javax.swing.JButton btnExportFilesSelectedObservations;
    private javax.swing.JButton btnExportHTML;
    private javax.swing.JButton btnExportHTMLAdvanced;
    private javax.swing.JButton btnExportKML;
    private javax.swing.JButton btnExportWorkspace;
    private javax.swing.JButton btnExportXML;
    // End of variables declaration//GEN-END:variables
}
