package wildlog.ui.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import wildlog.data.dataobjects.Sighting;
import wildlog.data.dataobjects.interfaces.DataObjectWithWildLogFile;
import wildlog.data.enums.ActiveTimeSpesific;
import wildlog.data.enums.Age;
import wildlog.data.enums.Certainty;
import wildlog.data.enums.ElementType;
import wildlog.data.enums.GPSAccuracy;
import wildlog.data.enums.LifeStatus;
import wildlog.data.enums.Moonlight;
import wildlog.data.enums.Sex;
import wildlog.data.enums.SightingEvidence;
import wildlog.data.enums.TimeAccuracy;
import wildlog.data.enums.VisitType;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.helpers.CtrlClickSelectionModel;
import wildlog.ui.helpers.SpinnerFixer;
import wildlog.ui.reports.helpers.FilterProperties;
import wildlog.ui.reports.utils.UtilsReports;
import wildlog.ui.utils.UtilsTime;


public class FilterPropertiesDialog<T extends DataObjectWithWildLogFile> extends JDialog {
    private boolean selectionMade = false;
    private FilterProperties filterProperties;

    
    public FilterPropertiesDialog(JFrame inParent, List<T> inLstOriginalData, FilterProperties inFilterProperties) {
        super(inParent);
        initComponents();
        filterProperties = inFilterProperties;
        // Setup the escape key
        final FilterPropertiesDialog<T> thisHandler = this;
        thisHandler.getRootPane().registerKeyboardAction(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        thisHandler.setSelectionMade(false);
                        thisHandler.setVisible(false);
                        thisHandler.dispose();
                    }
                },
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);

        // Position the dialog
        UtilsDialog.setDialogToCenter(inParent, thisHandler);
        UtilsDialog.addModalBackgroundPanel(inParent, thisHandler);
        UtilsDialog.addModalBackgroundPanel(this, null);
        // Spinner stuff
        SpinnerFixer.configureSpinners(spnNumberOfElements);
        SpinnerFixer.configureSpinners(spnMoonphase);
        // Setup the selected values
        selectOldValues();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelect = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dtpStartDate = new org.jdesktop.swingx.JXDatePicker();
        dtpEndDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        spnStartTime = new javax.swing.JSpinner();
        spnEndTime = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        lsbCertainty = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        lsbGPSAccuracy = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        lsbTimeAccuracy = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTag = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        spnNumberOfElements = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lsbSex = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lsbAge = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        chkIndividualsLess = new javax.swing.JCheckBox();
        chkIndividualsMore = new javax.swing.JCheckBox();
        chkIncludeEmptyTags = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lsbEvidence = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        lsbLifeStatus = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsbVisitType = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsbElementType = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lsbTimeOfDay = new javax.swing.JList();
        spnMoonphase = new javax.swing.JSpinner();
        jScrollPane9 = new javax.swing.JScrollPane();
        lsbMoonlight = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTimeOfDayInfo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        chkMoonlightMore = new javax.swing.JCheckBox();
        chkMoonlightLess = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        btnSelectAll = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter Properties Selection");
        setMinimumSize(new java.awt.Dimension(550, 300));
        setModal(true);
        setResizable(false);

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Update.png"))); // NOI18N
        btnSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelect.setFocusPainted(false);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Select the properties to filter on:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dates"));

        dtpStartDate.setFormats(new SimpleDateFormat(UtilsTime.DEFAULT_WL_DATE_FORMAT_PATTERN));

        dtpEndDate.setFormats(new SimpleDateFormat(UtilsTime.DEFAULT_WL_DATE_FORMAT_PATTERN));

        jLabel1.setText("Start Date:");

        jLabel2.setText("End Date:");

        jLabel16.setText("Daily Start Time:");

        jLabel22.setText("Daily End Time:");

        spnStartTime.setModel(new javax.swing.SpinnerDateModel());
        spnStartTime.setEditor(new javax.swing.JSpinner.DateEditor(spnStartTime, "HH:mm"));

        spnEndTime.setModel(new javax.swing.SpinnerDateModel());
        spnEndTime.setEditor(new javax.swing.JSpinner.DateEditor(spnEndTime, "HH:mm"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(dtpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnStartTime)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(spnStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel22)
                    .addComponent(spnEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Certainty"));

        lsbCertainty.setBackground(new java.awt.Color(230, 226, 224));
        lsbCertainty.setForeground(new java.awt.Color(176, 153, 145));
        lsbCertainty.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(Certainty.values())));
        lsbCertainty.setFocusable(false);
        lsbCertainty.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbCertainty.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbCertainty.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane10.setViewportView(lsbCertainty);

        jLabel4.setText("Observation");

        jLabel6.setText("GPS Accuracy:");

        lsbGPSAccuracy.setBackground(new java.awt.Color(230, 226, 224));
        lsbGPSAccuracy.setForeground(new java.awt.Color(176, 153, 145));
        lsbGPSAccuracy.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(GPSAccuracy.values())));
        lsbGPSAccuracy.setFocusable(false);
        lsbGPSAccuracy.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbGPSAccuracy.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbGPSAccuracy.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane12.setViewportView(lsbGPSAccuracy);

        jLabel9.setText("Certainty:");

        lsbTimeAccuracy.setBackground(new java.awt.Color(230, 226, 224));
        lsbTimeAccuracy.setForeground(new java.awt.Color(176, 153, 145));
        lsbTimeAccuracy.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(TimeAccuracy.values())));
        lsbTimeAccuracy.setFocusable(false);
        lsbTimeAccuracy.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbTimeAccuracy.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbTimeAccuracy.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane11.setViewportView(lsbTimeAccuracy);

        jLabel5.setText("Time Accuracy:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Other Details"));

        jLabel10.setText("Tag:");

        txaTag.setColumns(20);
        txaTag.setRows(3);
        jScrollPane2.setViewportView(txaTag);

        jLabel11.setText("Individuals:");

        spnNumberOfElements.setModel(new javax.swing.SpinnerNumberModel(0, 0, 2147483647, 1));

        jLabel12.setText("Sex:");

        lsbSex.setBackground(new java.awt.Color(230, 226, 224));
        lsbSex.setForeground(new java.awt.Color(176, 153, 145));
        lsbSex.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(Sex.values())));
        lsbSex.setFocusable(false);
        lsbSex.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbSex.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbSex.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane4.setViewportView(lsbSex);

        lsbAge.setBackground(new java.awt.Color(230, 226, 224));
        lsbAge.setForeground(new java.awt.Color(176, 153, 145));
        lsbAge.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(Age.values())));
        lsbAge.setFocusable(false);
        lsbAge.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbAge.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbAge.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane5.setViewportView(lsbAge);

        jLabel13.setText("Age:");

        chkIndividualsLess.setText("and less");
        chkIndividualsLess.setFocusPainted(false);

        chkIndividualsMore.setText("and more");
        chkIndividualsMore.setFocusPainted(false);

        chkIncludeEmptyTags.setText("Include empty tags");
        chkIncludeEmptyTags.setFocusPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnNumberOfElements, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkIndividualsLess)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkIndividualsMore)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkIncludeEmptyTags)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkIncludeEmptyTags))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(spnNumberOfElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkIndividualsLess)
                                    .addComponent(chkIndividualsMore))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Categories"));

        jLabel15.setText("Evidence:");

        lsbEvidence.setBackground(new java.awt.Color(230, 226, 224));
        lsbEvidence.setForeground(new java.awt.Color(176, 153, 145));
        lsbEvidence.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(SightingEvidence.values())));
        lsbEvidence.setFocusable(false);
        lsbEvidence.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbEvidence.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbEvidence.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane7.setViewportView(lsbEvidence);

        lsbLifeStatus.setBackground(new java.awt.Color(230, 226, 224));
        lsbLifeStatus.setForeground(new java.awt.Color(176, 153, 145));
        lsbLifeStatus.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(LifeStatus.values())));
        lsbLifeStatus.setFocusable(false);
        lsbLifeStatus.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbLifeStatus.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbLifeStatus.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane6.setViewportView(lsbLifeStatus);

        jLabel14.setText("Life Status:");

        lsbVisitType.setBackground(new java.awt.Color(230, 226, 224));
        lsbVisitType.setForeground(new java.awt.Color(176, 153, 145));
        lsbVisitType.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(VisitType.values())));
        lsbVisitType.setFocusable(false);
        lsbVisitType.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbVisitType.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbVisitType.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane1.setViewportView(lsbVisitType);

        jLabel3.setText("Period Types:");

        jLabel8.setText("Creature Type:");

        lsbElementType.setBackground(new java.awt.Color(230, 226, 224));
        lsbElementType.setForeground(new java.awt.Color(176, 153, 145));
        lsbElementType.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(ElementType.values())));
        lsbElementType.setFocusable(false);
        lsbElementType.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbElementType.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbElementType.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane3.setViewportView(lsbElementType);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sun And Moon Phase"));

        jLabel19.setText("Moonlight:");

        lsbTimeOfDay.setBackground(new java.awt.Color(230, 226, 224));
        lsbTimeOfDay.setForeground(new java.awt.Color(176, 153, 145));
        lsbTimeOfDay.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(ActiveTimeSpesific.values())));
        lsbTimeOfDay.setFocusable(false);
        lsbTimeOfDay.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbTimeOfDay.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbTimeOfDay.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane8.setViewportView(lsbTimeOfDay);

        spnMoonphase.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        lsbMoonlight.setBackground(new java.awt.Color(230, 226, 224));
        lsbMoonlight.setForeground(new java.awt.Color(176, 153, 145));
        lsbMoonlight.setModel(new DefaultComboBoxModel(UtilsReports.removeEmptyEntries(Moonlight.values())));
        lsbMoonlight.setFocusable(false);
        lsbMoonlight.setSelectionBackground(new java.awt.Color(193, 209, 179));
        lsbMoonlight.setSelectionForeground(new java.awt.Color(23, 38, 4));
        lsbMoonlight.setSelectionModel(new CtrlClickSelectionModel());
        jScrollPane9.setViewportView(lsbMoonlight);

        jLabel17.setText("Time of Day:");

        jLabel18.setText("Moonphase:");

        lblTimeOfDayInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblTimeOfDayInfo.setForeground(new java.awt.Color(102, 102, 102));
        lblTimeOfDayInfo.setText("More Info...");
        lblTimeOfDayInfo.setToolTipText("Click here to see the definitions for each category.");
        lblTimeOfDayInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTimeOfDayInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTimeOfDayInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimeOfDayInfoMousePressed(evt);
            }
        });

        jLabel21.setText("% full");

        chkMoonlightMore.setText("and more");
        chkMoonlightMore.setFocusPainted(false);

        chkMoonlightLess.setText("and less");
        chkMoonlightLess.setFocusPainted(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel17)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTimeOfDayInfo)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(8, 8, 8)
                                .addComponent(spnMoonphase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(chkMoonlightLess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkMoonlightMore)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimeOfDayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(spnMoonphase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkMoonlightLess)
                            .addComponent(chkMoonlightMore))))
                .addGap(5, 5, 5))
        );

        jLabel7.setText("Select the values you wish to filter on from the options below.");

        btnSelectAll.setText("Select All");
        btnSelectAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectAll.setFocusPainted(false);
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnClearAll.setText("Clear All");
        btnClearAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearAll.setFocusPainted(false);
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        selectionMade = true;
        if (filterProperties == null) {
            filterProperties = new FilterProperties();
        }
        filterProperties.setStartDate(UtilsTime.getLocalDateFromDate(dtpStartDate.getDate()));
        filterProperties.setEndDate(UtilsTime.getLocalDateFromDate(dtpEndDate.getDate()));
        filterProperties.setStartTime(UtilsTime.getLocalTimeFromDate((Date) spnStartTime.getValue()));
        filterProperties.setEndTime(UtilsTime.getLocalTimeFromDate((Date) spnEndTime.getValue()));
        filterProperties.setActiveTimes(lsbTimeOfDay.getSelectedValuesList());
        filterProperties.setMoonlights(lsbMoonlight.getSelectedValuesList());
        filterProperties.setMoonphase((int) spnMoonphase.getValue());
        filterProperties.setMoonphaseIsLess(chkMoonlightLess.isSelected());
        filterProperties.setMoonphaseIsMore(chkMoonlightMore.isSelected());
        filterProperties.setVisitTypes(lsbVisitType.getSelectedValuesList());
        filterProperties.setEvidences(lsbEvidence.getSelectedValuesList());
        filterProperties.setLifeStatuses(lsbLifeStatus.getSelectedValuesList());
        filterProperties.setTimeAccuracies(lsbTimeAccuracy.getSelectedValuesList());
        filterProperties.setCertainties(lsbCertainty.getSelectedValuesList());
        filterProperties.setGPSAccuracies(lsbGPSAccuracy.getSelectedValuesList());
        filterProperties.setAges(lsbAge.getSelectedValuesList());
        filterProperties.setSexes(lsbSex.getSelectedValuesList());
        filterProperties.setNumberOfElements((int) spnNumberOfElements.getValue());
        filterProperties.setNumberOfElementsIsLess(chkIndividualsLess.isSelected());
        filterProperties.setNumberOfElementsIsMore(chkIndividualsMore.isSelected());
        String[] lines = txaTag.getText().split("\\r?\\n");
        filterProperties.setTags(new ArrayList<>(lines.length));
        for (String tag : lines) {
            if (!tag.trim().isEmpty()) {
                filterProperties.getTags().add(tag);
            }
        }
        filterProperties.setIncludeEmptyTags(chkIncludeEmptyTags.isSelected());
        filterProperties.setElementTypes(lsbElementType.getSelectedValuesList());
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSelectActionPerformed

    private void lblTimeOfDayInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimeOfDayInfoMousePressed
        getGlassPane().setVisible(true);
        JOptionPane.showMessageDialog(this,
            ActiveTimeSpesific.getCompleteDescription(),
            "Time of Day Definitions", JOptionPane.INFORMATION_MESSAGE);
        getGlassPane().setVisible(false);
    }//GEN-LAST:event_lblTimeOfDayInfoMousePressed

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        filterProperties = null;
        selectOldValues();
    }//GEN-LAST:event_btnSelectAllActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        if (filterProperties == null) {
            filterProperties = new FilterProperties();
        }
        filterProperties.setStartDate(null);
        filterProperties.setEndDate(null);
        filterProperties.setStartTime(LocalTime.MIN);
        filterProperties.setEndTime(LocalTime.MAX);
        filterProperties.setActiveTimes(new ArrayList<>(0));
        filterProperties.setMoonlights(new ArrayList<>(0));
        filterProperties.setMoonphase(0);
        filterProperties.setMoonphaseIsLess(true);
        filterProperties.setMoonphaseIsMore(true);
        filterProperties.setVisitTypes(new ArrayList<>(0));
        filterProperties.setEvidences(new ArrayList<>(0));
        filterProperties.setLifeStatuses(new ArrayList<>(0));
        filterProperties.setTimeAccuracies(new ArrayList<>(0));
        filterProperties.setCertainties(new ArrayList<>(0));
        filterProperties.setGPSAccuracies(new ArrayList<>(0));
        filterProperties.setAges(new ArrayList<>(0));
        filterProperties.setSexes(new ArrayList<>(0));
        filterProperties.setNumberOfElements(0);
        filterProperties.setNumberOfElementsIsLess(true);
        filterProperties.setNumberOfElementsIsMore(true);
        filterProperties.setTags(new ArrayList<>(0));
        filterProperties.setIncludeEmptyTags(true);
        filterProperties.setElementTypes(new ArrayList<>(0));
        selectOldValues();
    }//GEN-LAST:event_btnClearAllActionPerformed

    public boolean isSelectionMade() {
        return selectionMade;
    }
    
    public void setSelectionMade(boolean inSelectionMade) {
        selectionMade = inSelectionMade;
    }

    public FilterProperties getSelectedFilterProperties() {
        return filterProperties;
    }
    
    private void selectOldValues() {
        if (filterProperties == null) {
            dtpStartDate.setDate(null);
            dtpEndDate.setDate(null);
            spnStartTime.setValue(UtilsTime.getDateFromLocalTime(LocalTime.MIN));
            spnEndTime.setValue(UtilsTime.getDateFromLocalTime(LocalTime.MAX));
            selectValuesInJList(lsbTimeOfDay, ActiveTimeSpesific.values());
            selectValuesInJList(lsbMoonlight, Moonlight.values());
            spnMoonphase.setValue(0);
            chkMoonlightLess.setSelected(true);
            chkMoonlightMore.setSelected(true);
            selectValuesInJList(lsbVisitType, VisitType.values());
            selectValuesInJList(lsbEvidence, SightingEvidence.values());
            selectValuesInJList(lsbLifeStatus, LifeStatus.values());
            selectValuesInJList(lsbTimeAccuracy, TimeAccuracy.values());
            selectValuesInJList(lsbCertainty, Certainty.values());
            selectValuesInJList(lsbGPSAccuracy, GPSAccuracy.values());
            selectValuesInJList(lsbAge, Age.values());
            selectValuesInJList(lsbSex, Sex.values());
            spnNumberOfElements.setValue(0);
            chkIndividualsLess.setSelected(true);
            chkIndividualsMore.setSelected(true);
            txaTag.setText("");
            chkIncludeEmptyTags.setSelected(true);
            selectValuesInJList(lsbElementType, ElementType.values());
        }
        else {
            dtpStartDate.setDate(UtilsTime.getDateFromLocalDate(filterProperties.getStartDate()));
            dtpEndDate.setDate(UtilsTime.getDateFromLocalDate(filterProperties.getEndDate()));
            spnStartTime.setValue(UtilsTime.getDateFromLocalTime(filterProperties.getStartTime()));
            spnEndTime.setValue(UtilsTime.getDateFromLocalTime(filterProperties.getEndTime()));
            selectValuesInJList(lsbTimeOfDay, filterProperties.getActiveTimes());
            selectValuesInJList(lsbMoonlight, filterProperties.getMoonlights());
            spnMoonphase.setValue(filterProperties.getMoonphase());
            chkMoonlightLess.setSelected(filterProperties.isMoonphaseIsLess());
            chkMoonlightMore.setSelected(filterProperties.isMoonphaseIsMore());
            selectValuesInJList(lsbVisitType, filterProperties.getVisitTypes());
            selectValuesInJList(lsbEvidence, filterProperties.getEvidences());
            selectValuesInJList(lsbLifeStatus, filterProperties.getLifeStatuses());
            selectValuesInJList(lsbTimeAccuracy, filterProperties.getTimeAccuracies());
            selectValuesInJList(lsbCertainty, filterProperties.getCertainties());
            selectValuesInJList(lsbGPSAccuracy, filterProperties.getGPSAccuracies());
            selectValuesInJList(lsbAge, filterProperties.getAges());
            selectValuesInJList(lsbSex, filterProperties.getSexes());
            spnNumberOfElements.setValue(filterProperties.getNumberOfElements());
            chkIndividualsLess.setSelected(filterProperties.isNumberOfElementsIsLess());
            chkIndividualsMore.setSelected(filterProperties.isNumberOfElementsIsMore());
            String tagText = "";
            for (String tag : filterProperties.getTags()) {
                if (!tag.trim().isEmpty()) {
                    if (!tagText.isEmpty()) {
                        tagText = tagText + System.lineSeparator();
                    }
                    tagText = tagText + tag;
                }
            }
            txaTag.setText(tagText);
            chkIncludeEmptyTags.setSelected(filterProperties.isIncludeEmptyTags());
            selectValuesInJList(lsbElementType, filterProperties.getElementTypes());
        }
    }
    
    private void selectValuesInJList(JList inList, Object[] inValues) {
        selectValuesInJList(inList, Arrays.asList(inValues));
    }
    
    private void selectValuesInJList(JList inList, List inValues) {
        inList.clearSelection();
        for (int t = 0; t < inList.getModel().getSize(); t++) {
            for (Object object : inValues) {
                if (inList.getModel().getElementAt(t).equals(object)) {
                    inList.addSelectionInterval(t, t);
                }
            }
        }
    }
    
    public static boolean checkFilterPropertiesMatch(FilterProperties inFilterProperties, Sighting inSighting) {
        if (inFilterProperties != null) {
            // Date
            if (inFilterProperties.getStartDate() != null) {
                if (UtilsTime.getLocalDateFromDate(inSighting.getDate()).isBefore(inFilterProperties.getStartDate())) {
                    return false;
                }
            }
            if (inFilterProperties.getEndDate() != null) {
                if (UtilsTime.getLocalDateFromDate(inSighting.getDate()).isAfter(inFilterProperties.getEndDate())) {
                    return false;
                }
            }
            // Time
            if (inFilterProperties.getStartTime() != null) {
                if (UtilsTime.getLocalTimeFromDate(inSighting.getDate()).isBefore(inFilterProperties.getStartTime())) {
                    return false;
                }
            }
            if (inFilterProperties.getEndTime() != null) {
                if (UtilsTime.getLocalTimeFromDate(inSighting.getDate()).isAfter(inFilterProperties.getEndTime())) {
                    return false;
                }
            }
            // Time of day
            if (inFilterProperties.getActiveTimes() != null && !inFilterProperties.getActiveTimes().isEmpty()) {
                boolean found = false;
                for (ActiveTimeSpesific activeTimeSpesific : inFilterProperties.getActiveTimes()) {
                    if (activeTimeSpesific.equals(inSighting.getTimeOfDay())) {
                        found = true;
                        break;
                    }
                    if (activeTimeSpesific.equals(ActiveTimeSpesific.UNKNOWN)) {
                        if (inSighting.getTimeOfDay() == null || ActiveTimeSpesific.NONE.equals(inSighting.getTimeOfDay())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Moonlight
            if (inFilterProperties.getMoonlights() != null && !inFilterProperties.getMoonlights().isEmpty()) {
                boolean found = false;
                for (Moonlight moonlight : inFilterProperties.getMoonlights()) {
                    if (moonlight.equals(inSighting.getMoonlight())) {
                        found = true;
                        break;
                    }
                    if (moonlight.equals(Moonlight.UNKNOWN)) {
                        if (inSighting.getMoonlight() == null || Moonlight.NONE.equals(inSighting.getMoonlight())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Moonphase
            if (!(inFilterProperties.isMoonphaseIsLess() && inFilterProperties.isMoonphaseIsMore()) 
                    && inSighting.getMoonPhase() >= 0 && inFilterProperties.getMoonphase() >= 0) {
                boolean found = false;
                if (inFilterProperties.getMoonphase() == inSighting.getMoonPhase()) {
                    found = true;
                }
                else
                if (inFilterProperties.isMoonphaseIsLess() && inSighting.getMoonPhase() < inFilterProperties.getMoonphase()) {
                    found = true;
                }
                else
                if (inFilterProperties.isMoonphaseIsMore() && inSighting.getMoonPhase() > inFilterProperties.getMoonphase()) {
                    found = true;
                }
                if (!found) {
                    return false;
                }
            }

            // Visit Type
            if (inFilterProperties.getVisitTypes() != null && !inFilterProperties.getVisitTypes().isEmpty()) {
                boolean found = false;
                for (VisitType visitType : inFilterProperties.getVisitTypes()) {
                    if (visitType.equals(inSighting.getCachedVisitType())) {
                        found = true;
                        break;
                    }
                    if (visitType.equals(VisitType.UNKNOWN)) {
                        if (inSighting.getCachedVisitType() == null || VisitType.NONE.equals(inSighting.getCachedVisitType())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Evidence
            if (inFilterProperties.getEvidences() != null && !inFilterProperties.getEvidences().isEmpty()) {
                boolean found = false;
                for (SightingEvidence sightingEvidence : inFilterProperties.getEvidences()) {
                    if (sightingEvidence.equals(inSighting.getSightingEvidence())) {
                        found = true;
                        break;
                    }
                    if (sightingEvidence.equals(SightingEvidence.UNKNOWN)) {
                        if (inSighting.getSightingEvidence() == null || SightingEvidence.NONE.equals(inSighting.getSightingEvidence())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Life Status
            if (inFilterProperties.getLifeStatuses() != null && !inFilterProperties.getLifeStatuses().isEmpty()) {
                boolean found = false;
                for (LifeStatus lifeStatus : inFilterProperties.getLifeStatuses()) {
                    if (lifeStatus.equals(inSighting.getLifeStatus())) {
                        found = true;
                        break;
                    }
                    if (lifeStatus.equals(LifeStatus.UNKNOWN)) {
                        if (inSighting.getLifeStatus() == null || LifeStatus.NONE.equals(inSighting.getLifeStatus())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Time Accuracy
            if (inFilterProperties.getTimeAccuracies() != null && !inFilterProperties.getTimeAccuracies().isEmpty()) {
                boolean found = false;
                for (TimeAccuracy timeAccuracy : inFilterProperties.getTimeAccuracies()) {
                    if (timeAccuracy.equals(inSighting.getTimeAccuracy())) {
                        found = true;
                        break;
                    }
                    if (timeAccuracy.equals(TimeAccuracy.UNKNOWN)) {
                        if (inSighting.getTimeAccuracy() == null || TimeAccuracy.NONE.equals(inSighting.getTimeAccuracy())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Sighting Certianty
            if (inFilterProperties.getCertainties() != null && !inFilterProperties.getCertainties().isEmpty()) {
                boolean found = false;
                for (Certainty certainty : inFilterProperties.getCertainties()) {
                    if (certainty.equals(inSighting.getCertainty())) {
                        found = true;
                        break;
                    }
                    if (certainty.equals(Certainty.UNKNOWN)) {
                        if (inSighting.getCertainty() == null || Certainty.NONE.equals(inSighting.getCertainty())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // GPS Certainty
            if (inFilterProperties.getGPSAccuracies() != null && !inFilterProperties.getGPSAccuracies().isEmpty()) {
                boolean found = false;
                for (GPSAccuracy gpsAccuracy : inFilterProperties.getGPSAccuracies()) {
                    if (gpsAccuracy.equals(inSighting.getGPSAccuracy())) {
                        found = true;
                        break;
                    }
                    if (gpsAccuracy.equals(GPSAccuracy.UNKNOWN)) {
                        if (inSighting.getGPSAccuracy() == null || GPSAccuracy.NONE.equals(inSighting.getGPSAccuracy())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Age
            if (inFilterProperties.getAges() != null && !inFilterProperties.getAges().isEmpty()) {
                boolean found = false;
                for (Age age : inFilterProperties.getAges()) {
                    if (age.equals(inSighting.getAge())) {
                        found = true;
                        break;
                    }
                    if (age.equals(Age.UNKNOWN)) {
                        if (inSighting.getAge() == null || Age.NONE.equals(inSighting.getAge())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Sex
            if (inFilterProperties.getSexes() != null && !inFilterProperties.getSexes().isEmpty()) {
                boolean found = false;
                for (Sex sex : inFilterProperties.getSexes()) {
                    if (sex.equals(inSighting.getSex())) {
                        found = true;
                        break;
                    }
                    if (sex.equals(Sex.UNKNOWN)) {
                        if (inSighting.getSex() == null || Sex.NONE.equals(inSighting.getSex())) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Number of individuals
            if (!(inFilterProperties.isNumberOfElementsIsLess() && inFilterProperties.isNumberOfElementsIsMore()) 
                    && inSighting.getNumberOfElements() >= 0 && inFilterProperties.getNumberOfElements() >= 0) {
                boolean found = false;
                if (inFilterProperties.getNumberOfElements() == inSighting.getNumberOfElements()) {
                    found = true;
                }
                else
                if (inFilterProperties.isNumberOfElementsIsLess() && inSighting.getNumberOfElements() < inFilterProperties.getNumberOfElements()) {
                    found = true;
                }
                else
                if (inFilterProperties.isNumberOfElementsIsMore() && inSighting.getNumberOfElements() > inFilterProperties.getNumberOfElements()) {
                    found = true;
                }
                if (!found) {
                    return false;
                }
            }
            // Tag
            if (inSighting.getTag() == null || inSighting.getTag().trim().isEmpty()) {
                if (!inFilterProperties.isIncludeEmptyTags()) {
                    return false;
                }
            }
            else
            if (inFilterProperties.getTags() != null && !inFilterProperties.getTags().isEmpty()) {
                boolean found = false;
                for (String tag : inFilterProperties.getTags()) {
                    if (!tag.trim().isEmpty() && inSighting.getTag().trim().toLowerCase().contains(tag.trim().toLowerCase())) {
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    return false;
                }
            }
            // Element Type
            if (inFilterProperties.getElementTypes()!= null && !inFilterProperties.getElementTypes().isEmpty()) {
                boolean found = false;
                for (ElementType elementType : inFilterProperties.getElementTypes()) {
                    if (elementType.equals(inSighting.getCachedElementType())) {
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    return false;
                }
            }
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JCheckBox chkIncludeEmptyTags;
    private javax.swing.JCheckBox chkIndividualsLess;
    private javax.swing.JCheckBox chkIndividualsMore;
    private javax.swing.JCheckBox chkMoonlightLess;
    private javax.swing.JCheckBox chkMoonlightMore;
    private org.jdesktop.swingx.JXDatePicker dtpEndDate;
    private org.jdesktop.swingx.JXDatePicker dtpStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblTimeOfDayInfo;
    private javax.swing.JList lsbAge;
    private javax.swing.JList lsbCertainty;
    private javax.swing.JList lsbElementType;
    private javax.swing.JList lsbEvidence;
    private javax.swing.JList lsbGPSAccuracy;
    private javax.swing.JList lsbLifeStatus;
    private javax.swing.JList lsbMoonlight;
    private javax.swing.JList lsbSex;
    private javax.swing.JList lsbTimeAccuracy;
    private javax.swing.JList lsbTimeOfDay;
    private javax.swing.JList lsbVisitType;
    private javax.swing.JSpinner spnEndTime;
    private javax.swing.JSpinner spnMoonphase;
    private javax.swing.JSpinner spnNumberOfElements;
    private javax.swing.JSpinner spnStartTime;
    private javax.swing.JTextArea txaTag;
    // End of variables declaration//GEN-END:variables
}
