package wildlog.ui.dialogs;

import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.Element;
import wildlog.data.dataobjects.Location;
import wildlog.data.dataobjects.Visit;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.reports.ReportElementSightingsByMoon;
import wildlog.ui.reports.ReportElementSightingsBySun;
import wildlog.ui.reports.ReportLocationSightingsByMoon;
import wildlog.ui.reports.ReportLocationSightingsBySun;
import wildlog.ui.reports.ReportLocationSightingsByType;
import wildlog.ui.reports.ReportLocationSpeciesCurve;
import wildlog.ui.reports.ReportSightingByElement;
import wildlog.ui.reports.ReportSightingByLocation;
import wildlog.ui.reports.ReportVisitSightingsBySun;


public class ReportingDialog extends JDialog {
    private WildLogApp app;
    private Location location;
    private Element element;
    private Visit visit;
    private Date startDate;
    private Date endDate;

    public ReportingDialog(WildLogApp inApp,
            Location inLocationToMap,
            Element inElementToMap,
            Visit inVisit,
            Date inStartDate,
            Date inEndDate) {
        super(inApp.getMainFrame());
        // Set passed in values
        app = inApp;
        location = inLocationToMap;
        element = inElementToMap;
        visit = inVisit;
        startDate = inStartDate;
        endDate = inEndDate;

        // Auto generated code
        initComponents();

        // Determine what buttons to show
        if (location == null) {
            btnLocationMoon.setVisible(false);
            btnLocationSun.setVisible(false);
            btnLocationType.setVisible(false);
            btnLocationSpeciesCurve.setVisible(false);
        }
        if (element == null) {
            btnElementMoon.setVisible(false);
            btnElementSun.setVisible(false);
        }
        if (visit == null) {
            btnVisitSun.setVisible(false);
            btnVisitBulkImportView.setVisible(false);
        }
        if (startDate == null || endDate == null) {
            btnSightingDateElement.setVisible(false);
            btnSightingDateLocation.setVisible(false);
        }

        // Pack
        pack();

        // Setup the default behavior
        UtilsDialog.setDialogToCenter(app.getMainFrame(), this);
        UtilsDialog.addEscapeKeyListener(this);
        UtilsDialog.addModalBackgroundPanel(app.getMainFrame(), this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLocationMoon = new javax.swing.JButton();
        btnLocationSun = new javax.swing.JButton();
        btnLocationType = new javax.swing.JButton();
        btnLocationSpeciesCurve = new javax.swing.JButton();
        btnElementMoon = new javax.swing.JButton();
        btnElementSun = new javax.swing.JButton();
        btnVisitSun = new javax.swing.JButton();
        btnSightingDateLocation = new javax.swing.JButton();
        btnSightingDateElement = new javax.swing.JButton();
        btnVisitBulkImportView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Available Reports");
        setIconImage(new ImageIcon(app.getClass().getResource("resources/icons/Report.gif")).getImage());
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        btnLocationMoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnLocationMoon.setText("Observations by Moon Phase");
        btnLocationMoon.setFocusPainted(false);
        btnLocationMoon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLocationMoon.setIconTextGap(10);
        btnLocationMoon.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnLocationMoon.setMaximumSize(new java.awt.Dimension(250, 35));
        btnLocationMoon.setMinimumSize(new java.awt.Dimension(250, 35));
        btnLocationMoon.setName("btnLocationMoon"); // NOI18N
        btnLocationMoon.setPreferredSize(new java.awt.Dimension(250, 35));
        btnLocationMoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationMoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocationMoon);

        btnLocationSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnLocationSun.setText("Observations by Sun Phase");
        btnLocationSun.setFocusPainted(false);
        btnLocationSun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLocationSun.setIconTextGap(10);
        btnLocationSun.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnLocationSun.setMaximumSize(new java.awt.Dimension(250, 35));
        btnLocationSun.setMinimumSize(new java.awt.Dimension(250, 35));
        btnLocationSun.setName("btnLocationSun"); // NOI18N
        btnLocationSun.setPreferredSize(new java.awt.Dimension(250, 35));
        btnLocationSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationSunActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocationSun);

        btnLocationType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnLocationType.setText("Observations by Type");
        btnLocationType.setFocusPainted(false);
        btnLocationType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLocationType.setIconTextGap(10);
        btnLocationType.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnLocationType.setMaximumSize(new java.awt.Dimension(250, 35));
        btnLocationType.setMinimumSize(new java.awt.Dimension(250, 35));
        btnLocationType.setName("btnLocationType"); // NOI18N
        btnLocationType.setPreferredSize(new java.awt.Dimension(250, 35));
        btnLocationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationTypeActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocationType);

        btnLocationSpeciesCurve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnLocationSpeciesCurve.setText("Species Accumulation Curve");
        btnLocationSpeciesCurve.setFocusPainted(false);
        btnLocationSpeciesCurve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLocationSpeciesCurve.setIconTextGap(10);
        btnLocationSpeciesCurve.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnLocationSpeciesCurve.setMaximumSize(new java.awt.Dimension(250, 35));
        btnLocationSpeciesCurve.setMinimumSize(new java.awt.Dimension(250, 35));
        btnLocationSpeciesCurve.setName("btnLocationSpeciesCurve"); // NOI18N
        btnLocationSpeciesCurve.setPreferredSize(new java.awt.Dimension(250, 35));
        btnLocationSpeciesCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationSpeciesCurveActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocationSpeciesCurve);

        btnElementMoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnElementMoon.setText("Observations by Moon Phase");
        btnElementMoon.setFocusPainted(false);
        btnElementMoon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnElementMoon.setIconTextGap(10);
        btnElementMoon.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnElementMoon.setMaximumSize(new java.awt.Dimension(250, 35));
        btnElementMoon.setMinimumSize(new java.awt.Dimension(250, 35));
        btnElementMoon.setName("btnElementMoon"); // NOI18N
        btnElementMoon.setPreferredSize(new java.awt.Dimension(250, 35));
        btnElementMoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementMoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnElementMoon);

        btnElementSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnElementSun.setText("Observations by Sun Phase");
        btnElementSun.setFocusPainted(false);
        btnElementSun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnElementSun.setIconTextGap(10);
        btnElementSun.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnElementSun.setMaximumSize(new java.awt.Dimension(250, 35));
        btnElementSun.setMinimumSize(new java.awt.Dimension(250, 35));
        btnElementSun.setName("btnElementSun"); // NOI18N
        btnElementSun.setPreferredSize(new java.awt.Dimension(250, 35));
        btnElementSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementSunActionPerformed(evt);
            }
        });
        getContentPane().add(btnElementSun);

        btnVisitSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnVisitSun.setText("Observations by Sun Phase");
        btnVisitSun.setFocusPainted(false);
        btnVisitSun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVisitSun.setIconTextGap(10);
        btnVisitSun.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnVisitSun.setMaximumSize(new java.awt.Dimension(250, 35));
        btnVisitSun.setMinimumSize(new java.awt.Dimension(250, 35));
        btnVisitSun.setName("btnVisitSun"); // NOI18N
        btnVisitSun.setPreferredSize(new java.awt.Dimension(250, 35));
        btnVisitSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitSunActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisitSun);

        btnSightingDateLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnSightingDateLocation.setText("Observations by Date and Place");
        btnSightingDateLocation.setFocusPainted(false);
        btnSightingDateLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSightingDateLocation.setIconTextGap(10);
        btnSightingDateLocation.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnSightingDateLocation.setMaximumSize(new java.awt.Dimension(250, 35));
        btnSightingDateLocation.setMinimumSize(new java.awt.Dimension(250, 35));
        btnSightingDateLocation.setName("btnSightingDateLocation"); // NOI18N
        btnSightingDateLocation.setPreferredSize(new java.awt.Dimension(250, 35));
        btnSightingDateLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSightingDateLocationActionPerformed(evt);
            }
        });
        getContentPane().add(btnSightingDateLocation);

        btnSightingDateElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Report.gif"))); // NOI18N
        btnSightingDateElement.setText("Observations by Date and Creature");
        btnSightingDateElement.setFocusPainted(false);
        btnSightingDateElement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSightingDateElement.setIconTextGap(10);
        btnSightingDateElement.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnSightingDateElement.setMaximumSize(new java.awt.Dimension(250, 35));
        btnSightingDateElement.setMinimumSize(new java.awt.Dimension(250, 35));
        btnSightingDateElement.setName("btnSightingDateElement"); // NOI18N
        btnSightingDateElement.setPreferredSize(new java.awt.Dimension(250, 35));
        btnSightingDateElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSightingDateElementActionPerformed(evt);
            }
        });
        getContentPane().add(btnSightingDateElement);

        btnVisitBulkImportView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Bulk Impor Large.png"))); // NOI18N
        btnVisitBulkImportView.setText("Advanced Observation View");
        btnVisitBulkImportView.setEnabled(false);
        btnVisitBulkImportView.setFocusPainted(false);
        btnVisitBulkImportView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVisitBulkImportView.setIconTextGap(10);
        btnVisitBulkImportView.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnVisitBulkImportView.setMaximumSize(new java.awt.Dimension(250, 35));
        btnVisitBulkImportView.setMinimumSize(new java.awt.Dimension(250, 35));
        btnVisitBulkImportView.setName("btnVisitBulkImportView"); // NOI18N
        btnVisitBulkImportView.setPreferredSize(new java.awt.Dimension(250, 35));
        btnVisitBulkImportView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitBulkImportViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisitBulkImportView);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocationMoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationMoonActionPerformed
        JFrame report = new ReportLocationSightingsByMoon(location, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnLocationMoonActionPerformed

    private void btnLocationSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationSunActionPerformed
        JFrame report = new ReportLocationSightingsBySun(location, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnLocationSunActionPerformed

    private void btnLocationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationTypeActionPerformed
        JFrame report = new ReportLocationSightingsByType(location, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnLocationTypeActionPerformed

    private void btnLocationSpeciesCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationSpeciesCurveActionPerformed
        JFrame report = new ReportLocationSpeciesCurve(location, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnLocationSpeciesCurveActionPerformed

    private void btnElementMoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementMoonActionPerformed
        JFrame report = new ReportElementSightingsByMoon(element, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnElementMoonActionPerformed

    private void btnElementSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementSunActionPerformed
        JFrame report = new ReportElementSightingsBySun(element, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnElementSunActionPerformed

    private void btnVisitSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitSunActionPerformed
        JFrame report = new ReportVisitSightingsBySun(visit, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnVisitSunActionPerformed

    private void btnSightingDateLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSightingDateLocationActionPerformed
        JFrame report = new ReportSightingByLocation(startDate, endDate, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnSightingDateLocationActionPerformed

    private void btnSightingDateElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSightingDateElementActionPerformed
        JFrame report = new ReportSightingByElement(startDate, endDate, app);
        report.setVisible(true);
        this.dispose();
        report.toFront();
    }//GEN-LAST:event_btnSightingDateElementActionPerformed

    private void btnVisitBulkImportViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitBulkImportViewActionPerformed
        // TODO: implement 'n "report" wat lyk soos 'n "bulk import view"
    }//GEN-LAST:event_btnVisitBulkImportViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElementMoon;
    private javax.swing.JButton btnElementSun;
    private javax.swing.JButton btnLocationMoon;
    private javax.swing.JButton btnLocationSpeciesCurve;
    private javax.swing.JButton btnLocationSun;
    private javax.swing.JButton btnLocationType;
    private javax.swing.JButton btnSightingDateElement;
    private javax.swing.JButton btnSightingDateLocation;
    private javax.swing.JButton btnVisitBulkImportView;
    private javax.swing.JButton btnVisitSun;
    // End of variables declaration//GEN-END:variables
}
