package wildlog.ui.report;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JLabel;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.Element;
import wildlog.data.dataobjects.Location;
import wildlog.data.dataobjects.Sighting;
import wildlog.data.dataobjects.Visit;
import wildlog.data.enums.ActiveTimeSpesific;
import wildlog.data.enums.VisitType;
import wildlog.ui.report.chart.BarChart;
import wildlog.ui.report.chart.BarChartEntity;
import wildlog.ui.report.helpers.MoonReportHelper;

/**
 *
 * @author Henry
 */
public class ReportLocation extends javax.swing.JFrame {
    private boolean usePrimaryName = true;
    private boolean viewReport1 = true;
    private boolean viewReport2 = false;
    private boolean viewReport3 = false;
    private boolean viewReport4 = false;
    private Location location;
    private BarChart chartTime;
    private BarChart chartType;
    private BarChart chartSpecies;
    private List<Visit> visits;
    private WildLogApp app;


    /** Creates new form ReportLocation */
    public ReportLocation(Location inLocation, WildLogApp inApp) {
        app = inApp;
        location = inLocation;
        
        initComponents();

        Visit tempVisit = new Visit();
        tempVisit.setLocationName(location.getName());
        visits = app.getDBI().list(tempVisit);
        doReport1();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNumberOfVisits = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNumberOfSightings = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNumberOfElements = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDaySightings = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNightSightings = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFirstVisit = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblActiveDays = new javax.swing.JLabel();
        lblLegend = new javax.swing.JLabel();
        lblRemoteCamera = new javax.swing.JLabel();
        lblDayVisit = new javax.swing.JLabel();
        lblVacation = new javax.swing.JLabel();
        lblAtlas = new javax.swing.JLabel();
        scrReport = new javax.swing.JScrollPane();
        pnlScrollPane = new javax.swing.JPanel();
        lblNight = new javax.swing.JLabel();
        lblDawn = new javax.swing.JLabel();
        lblMorning = new javax.swing.JLabel();
        lblMidDay = new javax.swing.JLabel();
        lblAfternoon = new javax.swing.JLabel();
        lblDusk = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        lblMoonlightDay = new javax.swing.JLabel();
        lblNoMoonDay = new javax.swing.JLabel();
        lblMoonlightNight = new javax.swing.JLabel();
        lblNoMoonNight = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPrint = new javax.swing.JMenu();
        mnuPrintReport = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnuLoadReport1 = new javax.swing.JMenuItem();
        mnuLoadReport4 = new javax.swing.JMenuItem();
        mnuLoadReport2 = new javax.swing.JMenuItem();
        mnuLoadReport3 = new javax.swing.JMenuItem();
        mnuExtra = new javax.swing.JMenu();
        mnuName = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Location Report: " + location.getName());
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wildlog.WildLogApp.class).getContext().getResourceMap(ReportLocation.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setForeground(resourceMap.getColor("Form.foreground")); // NOI18N
        setMinimumSize(new java.awt.Dimension(550, 750));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(resourceMap.getFont("lblName.font")); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText(resourceMap.getString("lblName.text")); // NOI18N
        lblName.setName("lblName"); // NOI18N
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblNumberOfVisits.setText(resourceMap.getString("lblNumberOfVisits.text")); // NOI18N
        lblNumberOfVisits.setName("lblNumberOfVisits"); // NOI18N
        getContentPane().add(lblNumberOfVisits, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        jLabel3.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblNumberOfSightings.setText(resourceMap.getString("lblNumberOfSightings.text")); // NOI18N
        lblNumberOfSightings.setName("lblNumberOfSightings"); // NOI18N
        getContentPane().add(lblNumberOfSightings, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        lblNumberOfElements.setText(resourceMap.getString("lblNumberOfElements.text")); // NOI18N
        lblNumberOfElements.setName("lblNumberOfElements"); // NOI18N
        getContentPane().add(lblNumberOfElements, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 30, -1, -1));

        jLabel7.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblDaySightings.setText(resourceMap.getString("lblDaySightings.text")); // NOI18N
        lblDaySightings.setName("lblDaySightings"); // NOI18N
        getContentPane().add(lblDaySightings, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 50, 50, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        lblNightSightings.setText(resourceMap.getString("lblNightSightings.text")); // NOI18N
        lblNightSightings.setName("lblNightSightings"); // NOI18N
        getContentPane().add(lblNightSightings, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 50, 60, -1));

        jLabel6.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel9.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        lblFirstVisit.setText(resourceMap.getString("lblFirstVisit.text")); // NOI18N
        lblFirstVisit.setName("lblFirstVisit"); // NOI18N
        getContentPane().add(lblFirstVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, -1));

        lblLastVisit.setText(resourceMap.getString("lblLastVisit.text")); // NOI18N
        lblLastVisit.setName("lblLastVisit"); // NOI18N
        getContentPane().add(lblLastVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 120, -1));

        jLabel12.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        lblActiveDays.setText(resourceMap.getString("lblActiveDays.text")); // NOI18N
        lblActiveDays.setName("lblActiveDays"); // NOI18N
        getContentPane().add(lblActiveDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 50, 90, -1));

        lblLegend.setText(resourceMap.getString("lblLegend.text")); // NOI18N
        lblLegend.setName("lblLegend"); // NOI18N
        getContentPane().add(lblLegend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 725, -1, -1));

        lblRemoteCamera.setFont(resourceMap.getFont("lblRemoteCamera.font")); // NOI18N
        lblRemoteCamera.setForeground(resourceMap.getColor("lblRemoteCamera.foreground")); // NOI18N
        lblRemoteCamera.setText(resourceMap.getString("lblRemoteCamera.text")); // NOI18N
        lblRemoteCamera.setName("lblRemoteCamera"); // NOI18N
        getContentPane().add(lblRemoteCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 725, -1, -1));

        lblDayVisit.setFont(resourceMap.getFont("lblDayVisit.font")); // NOI18N
        lblDayVisit.setForeground(resourceMap.getColor("lblDayVisit.foreground")); // NOI18N
        lblDayVisit.setText(resourceMap.getString("lblDayVisit.text")); // NOI18N
        lblDayVisit.setName("lblDayVisit"); // NOI18N
        getContentPane().add(lblDayVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 725, -1, -1));

        lblVacation.setFont(resourceMap.getFont("lblVacation.font")); // NOI18N
        lblVacation.setForeground(resourceMap.getColor("lblVacation.foreground")); // NOI18N
        lblVacation.setText(resourceMap.getString("lblVacation.text")); // NOI18N
        lblVacation.setName("lblVacation"); // NOI18N
        getContentPane().add(lblVacation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 725, -1, -1));

        lblAtlas.setFont(resourceMap.getFont("lblAtlas.font")); // NOI18N
        lblAtlas.setForeground(resourceMap.getColor("lblAtlas.foreground")); // NOI18N
        lblAtlas.setText(resourceMap.getString("lblAtlas.text")); // NOI18N
        lblAtlas.setName("lblAtlas"); // NOI18N
        getContentPane().add(lblAtlas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 725, -1, -1));

        scrReport.setBorder(null);
        scrReport.setName("scrReport"); // NOI18N

        pnlScrollPane.setBackground(resourceMap.getColor("pnlScrollPane.background")); // NOI18N
        pnlScrollPane.setName("pnlScrollPane"); // NOI18N
        pnlScrollPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        scrReport.setViewportView(pnlScrollPane);

        getContentPane().add(scrReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 630));

        lblNight.setFont(resourceMap.getFont("lblNight.font")); // NOI18N
        lblNight.setForeground(resourceMap.getColor("lblNight.foreground")); // NOI18N
        lblNight.setText(resourceMap.getString("lblNight.text")); // NOI18N
        lblNight.setName("lblNight"); // NOI18N
        getContentPane().add(lblNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 725, 60, -1));

        lblDawn.setFont(resourceMap.getFont("lblDawn.font")); // NOI18N
        lblDawn.setForeground(resourceMap.getColor("lblDawn.foreground")); // NOI18N
        lblDawn.setText(resourceMap.getString("lblDawn.text")); // NOI18N
        lblDawn.setName("lblDawn"); // NOI18N
        getContentPane().add(lblDawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 725, 60, -1));

        lblMorning.setFont(resourceMap.getFont("lblMorning.font")); // NOI18N
        lblMorning.setForeground(resourceMap.getColor("lblMorning.foreground")); // NOI18N
        lblMorning.setText(resourceMap.getString("lblMorning.text")); // NOI18N
        lblMorning.setName("lblMorning"); // NOI18N
        getContentPane().add(lblMorning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 725, 80, -1));

        lblMidDay.setFont(resourceMap.getFont("lblMidDay.font")); // NOI18N
        lblMidDay.setForeground(resourceMap.getColor("lblMidDay.foreground")); // NOI18N
        lblMidDay.setText(resourceMap.getString("lblMidDay.text")); // NOI18N
        lblMidDay.setName("lblMidDay"); // NOI18N
        getContentPane().add(lblMidDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 725, 70, -1));

        lblAfternoon.setFont(resourceMap.getFont("lblAfternoon.font")); // NOI18N
        lblAfternoon.setForeground(resourceMap.getColor("lblAfternoon.foreground")); // NOI18N
        lblAfternoon.setText(resourceMap.getString("lblAfternoon.text")); // NOI18N
        lblAfternoon.setName("lblAfternoon"); // NOI18N
        getContentPane().add(lblAfternoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 725, 90, -1));

        lblDusk.setFont(resourceMap.getFont("lblDusk.font")); // NOI18N
        lblDusk.setForeground(resourceMap.getColor("lblDusk.foreground")); // NOI18N
        lblDusk.setText(resourceMap.getString("lblDusk.text")); // NOI18N
        lblDusk.setName("lblDusk"); // NOI18N
        getContentPane().add(lblDusk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 725, 50, -1));

        lblOther.setFont(resourceMap.getFont("lblOther.font")); // NOI18N
        lblOther.setForeground(resourceMap.getColor("lblOther.foreground")); // NOI18N
        lblOther.setText(resourceMap.getString("lblOther.text")); // NOI18N
        lblOther.setName("lblOther"); // NOI18N
        getContentPane().add(lblOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 725, 60, -1));

        lblMoonlightDay.setFont(resourceMap.getFont("lblMoonlightDay.font")); // NOI18N
        lblMoonlightDay.setForeground(resourceMap.getColor("lblMoonlightDay.foreground")); // NOI18N
        lblMoonlightDay.setText(resourceMap.getString("lblMoonlightDay.text")); // NOI18N
        lblMoonlightDay.setName("lblMoonlightDay"); // NOI18N
        getContentPane().add(lblMoonlightDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 725, 140, -1));

        lblNoMoonDay.setFont(resourceMap.getFont("lblNoMoonDay.font")); // NOI18N
        lblNoMoonDay.setForeground(resourceMap.getColor("lblNoMoonDay.foreground")); // NOI18N
        lblNoMoonDay.setText(resourceMap.getString("lblNoMoonDay.text")); // NOI18N
        lblNoMoonDay.setName("lblNoMoonDay"); // NOI18N
        getContentPane().add(lblNoMoonDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 725, 100, -1));

        lblMoonlightNight.setFont(resourceMap.getFont("lblMoonlightNight.font")); // NOI18N
        lblMoonlightNight.setForeground(resourceMap.getColor("lblMoonlightNight.foreground")); // NOI18N
        lblMoonlightNight.setText(resourceMap.getString("lblMoonlightNight.text")); // NOI18N
        lblMoonlightNight.setName("lblMoonlightNight"); // NOI18N
        getContentPane().add(lblMoonlightNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 725, 130, -1));

        lblNoMoonNight.setFont(resourceMap.getFont("lblNoMoonNight.font")); // NOI18N
        lblNoMoonNight.setForeground(resourceMap.getColor("lblNoMoonNight.foreground")); // NOI18N
        lblNoMoonNight.setText(resourceMap.getString("lblNoMoonNight.text")); // NOI18N
        lblNoMoonNight.setName("lblNoMoonNight"); // NOI18N
        getContentPane().add(lblNoMoonNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 725, 120, -1));

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnuPrint.setText(resourceMap.getString("mnuPrint.text")); // NOI18N
        mnuPrint.setName("mnuPrint"); // NOI18N

        mnuPrintReport.setText(resourceMap.getString("mnuPrintReport.text")); // NOI18N
        mnuPrintReport.setName("mnuPrintReport"); // NOI18N
        mnuPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrintReportActionPerformed(evt);
            }
        });
        mnuPrint.add(mnuPrintReport);

        jMenuBar1.add(mnuPrint);

        mnuReports.setText(resourceMap.getString("mnuReports.text")); // NOI18N
        mnuReports.setName("mnuReports"); // NOI18N

        mnuLoadReport1.setText(resourceMap.getString("mnuLoadReport1.text")); // NOI18N
        mnuLoadReport1.setName("mnuLoadReport1"); // NOI18N
        mnuLoadReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadReport1ActionPerformed(evt);
            }
        });
        mnuReports.add(mnuLoadReport1);

        mnuLoadReport4.setText(resourceMap.getString("mnuLoadReport4.text")); // NOI18N
        mnuLoadReport4.setName("mnuLoadReport4"); // NOI18N
        mnuLoadReport4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadReport4ActionPerformed(evt);
            }
        });
        mnuReports.add(mnuLoadReport4);

        mnuLoadReport2.setText(resourceMap.getString("mnuLoadReport2.text")); // NOI18N
        mnuLoadReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadReport2ActionPerformed(evt);
            }
        });
        mnuReports.add(mnuLoadReport2);

        mnuLoadReport3.setText(resourceMap.getString("mnuLoadReport3.text")); // NOI18N
        mnuLoadReport3.setName("mnuLoadReport3"); // NOI18N
        mnuLoadReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadReport3ActionPerformed(evt);
            }
        });
        mnuReports.add(mnuLoadReport3);

        jMenuBar1.add(mnuReports);

        mnuExtra.setText(resourceMap.getString("mnuExtra.text")); // NOI18N
        mnuExtra.setName("mnuExtra"); // NOI18N

        mnuName.setText(resourceMap.getString("mnuName.text")); // NOI18N
        mnuName.setName("mnuName"); // NOI18N
        mnuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNameActionPerformed(evt);
            }
        });
        mnuExtra.add(mnuName);

        jMenuBar1.add(mnuExtra);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrintReportActionPerformed
        try {
            final JFrame frame = this;
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setJobName("WildLog Location Report");
            pj.setCopies(1);
            PageFormat format = pj.defaultPage();
            format.setOrientation(PageFormat.PORTRAIT);
            pj.setPrintable(new Printable() {
                @Override
                public int print(Graphics pg, PageFormat pf, int pageNum) {
                    if (pageNum > 0) {
                        return Printable.NO_SUCH_PAGE;
                    }

                    frame.getContentPane().print(pg);

                    return Printable.PAGE_EXISTS;
                }
            });
            if (pj.printDialog() == false) {
                return;
            }
            pj.print();
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuPrintReportActionPerformed

    private void mnuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNameActionPerformed
        usePrimaryName = ! usePrimaryName;
        if (viewReport1) {
            doReport1();
            // Re-Draw
            repaint();
            setVisible(true);
        }
        else
        if (viewReport2) {
            doReport2();
            // Re-Draw
            repaint();
            setVisible(true);
        }
        else
        if (viewReport3) {
            doReport3();
            // Re-Draw
            repaint();
            setVisible(true);
        }
        else
        if (viewReport4) {
            doReport4();
            // Re-Draw
            repaint();
            setVisible(true);
        }
    }//GEN-LAST:event_mnuNameActionPerformed

    private void mnuLoadReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadReport1ActionPerformed
        viewReport1 = true;
        viewReport2 = false;
        viewReport3 = false;
        viewReport4 = false;
        usePrimaryName = true;
        doReport1();
        // Re-Draw
        repaint();
        setVisible(true);
    }//GEN-LAST:event_mnuLoadReport1ActionPerformed

    private void mnuLoadReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadReport2ActionPerformed
        viewReport1 = false;
        viewReport2 = true;
        viewReport3 = false;
        viewReport4 = false;
        usePrimaryName = true;
        doReport2();
        // Re-Draw
        repaint();
        setVisible(true);
    }//GEN-LAST:event_mnuLoadReport2ActionPerformed

    private void mnuLoadReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadReport3ActionPerformed
        viewReport1 = false;
        viewReport2 = false;
        viewReport3 = true;
        viewReport4 = false;
        usePrimaryName = true;
        doReport3();
        // Re-Draw
        repaint();
        setVisible(true);
    }//GEN-LAST:event_mnuLoadReport3ActionPerformed

    private void mnuLoadReport4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadReport4ActionPerformed
        viewReport1 = false;
        viewReport2 = false;
        viewReport3 = false;
        viewReport4 = true;
        usePrimaryName = true;
        doReport4();
        // Re-Draw
        repaint();
        setVisible(true);
    }//GEN-LAST:event_mnuLoadReport4ActionPerformed

    private void doReport1() {
        // Init report fields
        lblName.setText(location.getName());
        lblNumberOfVisits.setText(Integer.toString(visits.size()));
        int numOfSightings = 0;
        Set<String> numOfElements = new HashSet<String>();
        int numDaySightings = 0;
        int numNightSightings = 0;
        Date firstDate = null;
        Date lastDate = null;
        int activeDays = 0;

        // Add Charts
        if (chartTime != null)
            pnlScrollPane.remove(chartTime);
        if (chartType != null)
            pnlScrollPane.remove(chartType);
        if (chartSpecies != null)
            pnlScrollPane.remove(chartSpecies);
        chartTime = new BarChart(580, 630);
        for (Visit visit : visits) {
            if (visit.getStartDate() != null) {
                if (firstDate == null)
                    firstDate = visit.getStartDate();
                else
                if (visit.getStartDate().before(firstDate))
                    firstDate = visit.getStartDate();
            }
            if (visit.getEndDate() != null) {
                if (lastDate == null)
                    lastDate = visit.getEndDate();
                else
                if (visit.getEndDate().after(lastDate))
                    lastDate = visit.getEndDate();
            }
            if (visit.getStartDate() != null && visit.getEndDate() != null) {
                if (visit.getStartDate().before(visit.getEndDate()) || visit.getStartDate().equals(visit.getEndDate())) {
                    long diff = visit.getEndDate().getTime() - visit.getStartDate().getTime();
                    activeDays = activeDays + (int)Math.ceil((double)diff/60/60/24/1000) + 1;
                }
            }
            Sighting tempSighting = new Sighting();
            tempSighting.setVisitName(visit.getName());
            List<Sighting> sightings = app.getDBI().list(tempSighting);
            for (Sighting sighting : sightings) {
                numOfSightings++;
                numOfElements.add(sighting.getElementName());
                String nameToUse = "";
                if (usePrimaryName)
                    nameToUse = sighting.getElementName();
                else {
                    Element tempElement = app.getDBI().find(new Element(sighting.getElementName()));
                    if (tempElement.getOtherName() != null)
                        nameToUse = tempElement.getOtherName();
                }
                // Time
                if (sighting.getTimeOfDay() != null) {
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.DEEP_NIGHT)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1, lblNight.getForeground()));
                        numNightSightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.EARLY_MORNING)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblDawn.getForeground()));
                        numDaySightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.MORNING)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblMorning.getForeground()));
                        numDaySightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.MIDDAY) || sighting.getTimeOfDay().equals(ActiveTimeSpesific.MID_AFTERNOON) || sighting.getTimeOfDay().equals(ActiveTimeSpesific.MID_MORNING)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblMidDay.getForeground()));
                        numDaySightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.AFTERNOON)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblAfternoon.getForeground()));
                        numDaySightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.LATE_AFTERNOON)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblDusk.getForeground()));
                        numDaySightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.NONE)) {
                        chartTime.addBar(new BarChartEntity(nameToUse, sighting.getTimeOfDay().name(), 1,  lblOther.getForeground()));
                    }
                }
                else
                    chartTime.addBar(new BarChartEntity(nameToUse, ActiveTimeSpesific.NONE.name(), 1, lblOther.getForeground()));
            }
        }

        pnlScrollPane.add(chartTime);
        chartTime.paintComponent(pnlScrollPane.getGraphics());
        pnlScrollPane.setPreferredSize(new Dimension(580, chartTime.getChartHeight()));

        // Wrap up report fields
        lblNumberOfSightings.setText(Integer.toString(numOfSightings));
        lblNumberOfElements.setText(Integer.toString(numOfElements.size()));
        lblDaySightings.setText(Integer.toString(numDaySightings));
        lblNightSightings.setText(Integer.toString(numNightSightings));
        if (firstDate != null)
            lblFirstVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(firstDate));
        else
            lblFirstVisit.setText("Unknown");
        if (lastDate != null)
            lblLastVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(lastDate));
        else
            lblLastVisit.setText("Unknown");
        lblActiveDays.setText(Integer.toString(activeDays));

        // Setup Frame Look and Feel
        this.getContentPane().setBackground(Color.WHITE);

        lblLegend.setVisible(true);
        lblOther.setVisible(true);
        lblNight.setVisible(true);
        lblDawn.setVisible(true);
        lblMorning.setVisible(true);
        lblMidDay.setVisible(true);
        lblAfternoon.setVisible(true);
        lblDusk.setVisible(true);
        lblMoonlightDay.setVisible(false);
        lblNoMoonDay.setVisible(false);
        lblMoonlightNight.setVisible(false);
        lblNoMoonNight.setVisible(false);
        lblRemoteCamera.setVisible(false);
        lblVacation.setVisible(false);
        lblDayVisit.setVisible(false);
        lblAtlas.setVisible(false);
    }

    private void doReport4() {
        // Init report fields
        lblName.setText(location.getName());
        lblNumberOfVisits.setText(Integer.toString(visits.size()));
        int numOfSightings = 0;
        Set<String> numOfElements = new HashSet<String>();
        int numDaySightings = 0;
        int numNightSightings = 0;
        Date firstDate = null;
        Date lastDate = null;
        int activeDays = 0;

        // Add Charts
        if (chartTime != null)
            pnlScrollPane.remove(chartTime);
        if (chartType != null)
            pnlScrollPane.remove(chartType);
        if (chartSpecies != null)
            pnlScrollPane.remove(chartSpecies);
        chartTime = new BarChart(580, 630);
        for (Visit visit : visits) {
            if (visit.getStartDate() != null) {
                if (firstDate == null)
                    firstDate = visit.getStartDate();
                else
                if (visit.getStartDate().before(firstDate))
                    firstDate = visit.getStartDate();
            }
            if (visit.getEndDate() != null) {
                if (lastDate == null)
                    lastDate = visit.getEndDate();
                else
                if (visit.getEndDate().after(lastDate))
                    lastDate = visit.getEndDate();
            }
            if (visit.getStartDate() != null && visit.getEndDate() != null) {
                if (visit.getStartDate().before(visit.getEndDate()) || visit.getStartDate().equals(visit.getEndDate())) {
                    long diff = visit.getEndDate().getTime() - visit.getStartDate().getTime();
                    activeDays = activeDays + (int)Math.ceil((double)diff/60/60/24/1000) + 1;
                }
            }
            Sighting tempSighting = new Sighting();
            tempSighting.setVisitName(visit.getName());
            List<Sighting> sightings = app.getDBI().list(tempSighting);
            for (Sighting sighting : sightings) {
                numOfSightings++;
                numOfElements.add(sighting.getElementName());
                String nameToUse = "";
                if (usePrimaryName)
                    nameToUse = sighting.getElementName();
                else {
                    Element tempElement = app.getDBI().find(new Element(sighting.getElementName()));
                    if (tempElement.getOtherName() != null)
                        nameToUse = tempElement.getOtherName();
                }
                // Time
                if (sighting.getTimeOfDay() != null) {
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.DEEP_NIGHT)) {
                        // Night
                        numNightSightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.NONE)) {
                        // Do nothing
                    }
                    else {
                        // Day
                        numDaySightings++;
                    }
                }
                // Moon
                MoonReportHelper.addMoonInfoToChart(chartTime, sighting, new JLabel[]{lblMoonlightNight, lblNoMoonNight, lblMoonlightDay, lblNoMoonDay, lblOther});
            }
        }

        pnlScrollPane.add(chartTime);
        chartTime.paintComponent(pnlScrollPane.getGraphics());
        pnlScrollPane.setPreferredSize(new Dimension(580, chartTime.getChartHeight()));

        // Wrap up report fields
        lblNumberOfSightings.setText(Integer.toString(numOfSightings));
        lblNumberOfElements.setText(Integer.toString(numOfElements.size()));
        lblDaySightings.setText(Integer.toString(numDaySightings));
        lblNightSightings.setText(Integer.toString(numNightSightings));
        if (firstDate != null)
            lblFirstVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(firstDate));
        else
            lblFirstVisit.setText("Unknown");
        if (lastDate != null)
            lblLastVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(lastDate));
        else
            lblLastVisit.setText("Unknown");
        lblActiveDays.setText(Integer.toString(activeDays));

        // Setup Frame Look and Feel
        this.getContentPane().setBackground(Color.WHITE);

        lblLegend.setVisible(true);
        lblOther.setVisible(true);
        lblNight.setVisible(false);
        lblDawn.setVisible(false);
        lblMorning.setVisible(false);
        lblMidDay.setVisible(false);
        lblAfternoon.setVisible(false);
        lblDusk.setVisible(false);
        lblMoonlightDay.setVisible(true);
        lblNoMoonDay.setVisible(true);
        lblMoonlightNight.setVisible(true);
        lblNoMoonNight.setVisible(true);
        lblRemoteCamera.setVisible(false);
        lblVacation.setVisible(false);
        lblDayVisit.setVisible(false);
        lblAtlas.setVisible(false);
    }

    private void doReport2() {
        // Init report fields
        lblName.setText(location.getName());
        lblNumberOfVisits.setText(Integer.toString(visits.size()));
        int numOfSightings = 0;
        Set<String> numOfElements = new HashSet<String>();
        int numDaySightings = 0;
        int numNightSightings = 0;
        Date firstDate = null;
        Date lastDate = null;
        int activeDays = 0;

        // Add Charts
        if (chartTime != null)
            pnlScrollPane.remove(chartTime);
        if (chartType != null)
            pnlScrollPane.remove(chartType);
        if (chartSpecies != null)
            pnlScrollPane.remove(chartSpecies);
        chartType = new BarChart(580, 630);
        for (Visit visit : visits) {
            if (visit.getStartDate() != null) {
                if (firstDate == null)
                    firstDate = visit.getStartDate();
                else
                if (visit.getStartDate().before(firstDate))
                    firstDate = visit.getStartDate();
            }
            if (visit.getEndDate() != null) {
                if (lastDate == null)
                    lastDate = visit.getEndDate();
                else
                if (visit.getEndDate().after(lastDate))
                    lastDate = visit.getEndDate();
            }
            if (visit.getStartDate() != null && visit.getEndDate() != null) {
                if (visit.getStartDate().before(visit.getEndDate()) || visit.getStartDate().equals(visit.getEndDate())) {
                    long diff = visit.getEndDate().getTime() - visit.getStartDate().getTime();
                    activeDays = activeDays + (int)Math.ceil((double)diff/60/60/24/1000) + 1;
                }
            }
            Sighting tempSighting = new Sighting();
            tempSighting.setVisitName(visit.getName());
            List<Sighting> sightings = app.getDBI().list(tempSighting);
            for (Sighting sighting : sightings) {
                numOfSightings++;
                numOfElements.add(sighting.getElementName());
                String nameToUse = "";
                if (usePrimaryName)
                    nameToUse = sighting.getElementName();
                else {
                    Element tempElement = app.getDBI().find(new Element(sighting.getElementName()));
                    if (tempElement.getOtherName() != null)
                        nameToUse = tempElement.getOtherName();
                }
                // Time
                if (sighting.getTimeOfDay() != null) {
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.DEEP_NIGHT)) {
                        // Night
                        numNightSightings++;
                    }
                    else
                    if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.NONE)) {
                        // Do nothing
                    }
                    else {
                        // Day
                        numDaySightings++;
                    }
                }
                // Type
                if (visit.getType() != null) {
                    if (visit.getType().equals(VisitType.REMOTE_CAMERA))
                        chartType.addBar(new BarChartEntity(nameToUse, visit.getType().name(), 1, lblRemoteCamera.getForeground()));
                    else
                    if (visit.getType().equals(VisitType.DAY_VISIT))
                        chartType.addBar(new BarChartEntity(nameToUse, visit.getType().name(), 1, lblDayVisit.getForeground()));
                    else
                    if (visit.getType().equals(VisitType.VACATION))
                        chartType.addBar(new BarChartEntity(nameToUse, visit.getType().name(), 1, lblVacation.getForeground()));
                    else
                    if (visit.getType().equals(VisitType.BIRD_ATLASSING))
                        chartType.addBar(new BarChartEntity(nameToUse, visit.getType().name(), 1, lblAtlas.getForeground()));
                    else
                        chartType.addBar(new BarChartEntity(nameToUse, visit.getType().name(), 1, lblOther.getForeground()));
                }
                else
                    chartType.addBar(new BarChartEntity(nameToUse, VisitType.NONE.name(), 1, lblOther.getForeground()));
            }
        }

        pnlScrollPane.add(chartType);
        chartType.paintComponent(pnlScrollPane.getGraphics());
        pnlScrollPane.setPreferredSize(new Dimension(580, chartType.getChartHeight()));

        // Wrap up report fields
        lblNumberOfSightings.setText(Integer.toString(numOfSightings));
        lblNumberOfElements.setText(Integer.toString(numOfElements.size()));
        lblDaySightings.setText(Integer.toString(numDaySightings));
        lblNightSightings.setText(Integer.toString(numNightSightings));
        if (firstDate != null)
            lblFirstVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(firstDate));
        else
            lblFirstVisit.setText("Unknown");
        if (lastDate != null)
            lblLastVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(lastDate));
        else
            lblLastVisit.setText("Unknown");
        lblActiveDays.setText(Integer.toString(activeDays));

        // Setup Frame Look and Feel
        this.getContentPane().setBackground(Color.WHITE);

        lblLegend.setVisible(true);
        lblOther.setVisible(true);
        lblNight.setVisible(false);
        lblDawn.setVisible(false);
        lblMorning.setVisible(false);
        lblMidDay.setVisible(false);
        lblAfternoon.setVisible(false);
        lblDusk.setVisible(false);
        lblMoonlightDay.setVisible(false);
        lblNoMoonDay.setVisible(false);
        lblMoonlightNight.setVisible(false);
        lblNoMoonNight.setVisible(false);
        lblRemoteCamera.setVisible(true);
        lblVacation.setVisible(true);
        lblDayVisit.setVisible(true);
        lblAtlas.setVisible(true);
    }

    private void doReport3() {
        class ReportData implements Comparable<ReportData> {
            public Date dateAsDay;
            public int creatureCount;
            public String name;

            public ReportData(Date inDateAsDay, int inCreatureCount, String inName) {
                dateAsDay = inDateAsDay;
                creatureCount = inCreatureCount;
                name = inName;
            }

            @Override
            public int compareTo(ReportData inReportData) {
                return this.dateAsDay.compareTo(inReportData.dateAsDay);
            }
        }

        // Init report fields
        lblName.setText(location.getName());
        lblNumberOfVisits.setText(Integer.toString(visits.size()));
        int numOfSightings = 0;
        Set<String> numOfElements = new HashSet<String>();
        int numDaySightings = 0;
        int numNightSightings = 0;
        Date firstDate = null;
        Date lastDate = null;
        int activeDays = 0;

        // Add Charts
        if (chartTime != null)
            pnlScrollPane.remove(chartTime);
        if (chartType != null)
            pnlScrollPane.remove(chartType);
        if (chartSpecies != null)
            pnlScrollPane.remove(chartSpecies);
        chartSpecies = new BarChart(580, 630);
        // Get a sorted list of all visits with dates
        List<Visit> sortedVisits = new ArrayList<Visit>(visits.size());
        for (Visit visit : visits) {
            if (visit.getStartDate() != null && visit.getEndDate() != null) {
                if (visit.getStartDate().before(visit.getEndDate()) || visit.getStartDate().equals(visit.getEndDate())) {
                    if (sortedVisits.isEmpty()) {
                        sortedVisits.add(visit);
                    }
                    else {
                        boolean added = false;
                        for (int i = 0; i < sortedVisits.size(); i++) {
                            if (visit.getStartDate().before(sortedVisits.get(i).getStartDate())) {
                                sortedVisits.add(i, visit);
                                added = true;
                                break;
                            }
                        }
                        if (added == false) {
                            sortedVisits.add(visit);
                        }
                    }
                    long diff = visit.getEndDate().getTime() - visit.getStartDate().getTime();
                    activeDays = activeDays + (int)Math.ceil((double)diff/60/60/24/1000) + 1;
                }
            }
        }
        if (!sortedVisits.isEmpty()) {
            firstDate = sortedVisits.get(0).getStartDate();
            lastDate = sortedVisits.get(sortedVisits.size()-1).getEndDate();

            List<ReportData> tempData = new ArrayList<ReportData>();
            for (Visit visit : visits) {
                Sighting tempSighting = new Sighting();
                tempSighting.setVisitName(visit.getName());
                List<Sighting> sightings = app.getDBI().list(tempSighting);
                Collections.sort(sightings);
                for (Sighting sighting : sightings) {
                    numOfSightings++;
                    numOfElements.add(sighting.getElementName());
                    //if (!numOfElements.contains(sighting.getElement().getPrimaryName()))
                    //    chartSpecies.addBar(new BarChartEntity(sighting.getElement().getPrimaryName() + "-" + sighting.getDate(), visit.getName(), (numOfElements.size()), Color.yellow));
                    tempData.add(new ReportData(new Date(sighting.getDate().getYear(), sighting.getDate().getMonth(), sighting.getDate().getDate()), numOfElements.size(), sighting.getElementName()));

                    if (sighting.getTimeOfDay() != null) {
                        if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.DEEP_NIGHT)) {
                            numNightSightings++;
                        }
                        else
                        if (sighting.getTimeOfDay().equals(ActiveTimeSpesific.NONE)) {
                            // Do nothing
                        }
                        else {
                            numDaySightings++;
                        }
                    }
                }
            }

            List<ReportData> tempDataCore = new ArrayList<ReportData>(numOfElements.size());
            Collections.sort(tempData);
            Set<String> tempSet = new HashSet<String>(numOfElements.size());
            for (ReportData temp : tempData) {
                if (!tempSet.contains(temp.name)) {
                    tempSet.add(temp.name);
                    tempDataCore.add(new ReportData(temp.dateAsDay, tempSet.size(), ""));
                }
            }

            final double ROWS = 25.0;
            int interval = 1;
            int days = (int)((lastDate.getTime() - firstDate.getTime())/60/60/24/1000);
            if (days > ROWS)
                interval = (int)Math.ceil(days/ROWS);
            int count = 0;
            Map<Date, Integer> finalChartData = new HashMap<Date, Integer>((int)ROWS);
            int maxCreatures = 0;
            for (int t = 0; t <= days; t++) {
                for (ReportData data : tempDataCore) {
                    if (data.dateAsDay.equals(new Date(firstDate.getTime() + (long)t*60*60*24*1000))) {
                        maxCreatures = data.creatureCount;
                    }
                }
                if (count >= interval) {
                    finalChartData.put(new Date(firstDate.getTime() + (long)t*60*60*24*1000), maxCreatures);
                    count = 0;
                }
                count++;
            }
            if (count < interval && count > 0) {
                finalChartData.put(lastDate, maxCreatures);
            }

            for (Date temp : finalChartData.keySet()) {
                chartSpecies.addBar(new BarChartEntity(temp, "", finalChartData.get(temp), new Color(125, 198, 48)));
            }

        }
        else {
            firstDate = null;
            lastDate = null;
        }

        pnlScrollPane.add(chartSpecies);
        chartSpecies.paintComponent(pnlScrollPane.getGraphics());
        pnlScrollPane.setPreferredSize(new Dimension(580, chartSpecies.getChartHeight()));

        // Wrap up report fields
        lblNumberOfSightings.setText(Integer.toString(numOfSightings));
        lblNumberOfElements.setText(Integer.toString(numOfElements.size()));
        lblDaySightings.setText(Integer.toString(numDaySightings));
        lblNightSightings.setText(Integer.toString(numNightSightings));
        if (firstDate != null)
            lblFirstVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(firstDate));
        else
            lblFirstVisit.setText("Unknown");
        if (lastDate != null)
            lblLastVisit.setText(new SimpleDateFormat("dd MMM yyyy").format(lastDate));
        else
            lblLastVisit.setText("Unknown");
        lblActiveDays.setText(Integer.toString(activeDays));

        // Setup Frame Look and Feel
        this.getContentPane().setBackground(Color.WHITE);

        lblLegend.setVisible(false);
        lblOther.setVisible(false);
        lblNight.setVisible(false);
        lblDawn.setVisible(false);
        lblMorning.setVisible(false);
        lblMidDay.setVisible(false);
        lblAfternoon.setVisible(false);
        lblDusk.setVisible(false);
        lblMoonlightDay.setVisible(false);
        lblNoMoonDay.setVisible(false);
        lblMoonlightNight.setVisible(false);
        lblNoMoonNight.setVisible(false);
        lblRemoteCamera.setVisible(false);
        lblVacation.setVisible(false);
        lblDayVisit.setVisible(false);
        lblAtlas.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblActiveDays;
    private javax.swing.JLabel lblAfternoon;
    private javax.swing.JLabel lblAtlas;
    private javax.swing.JLabel lblDawn;
    private javax.swing.JLabel lblDaySightings;
    private javax.swing.JLabel lblDayVisit;
    private javax.swing.JLabel lblDusk;
    private javax.swing.JLabel lblFirstVisit;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblLegend;
    private javax.swing.JLabel lblMidDay;
    private javax.swing.JLabel lblMoonlightDay;
    private javax.swing.JLabel lblMoonlightNight;
    private javax.swing.JLabel lblMorning;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNight;
    private javax.swing.JLabel lblNightSightings;
    private javax.swing.JLabel lblNoMoonDay;
    private javax.swing.JLabel lblNoMoonNight;
    private javax.swing.JLabel lblNumberOfElements;
    private javax.swing.JLabel lblNumberOfSightings;
    private javax.swing.JLabel lblNumberOfVisits;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblRemoteCamera;
    private javax.swing.JLabel lblVacation;
    private javax.swing.JMenu mnuExtra;
    private javax.swing.JMenuItem mnuLoadReport1;
    private javax.swing.JMenuItem mnuLoadReport2;
    private javax.swing.JMenuItem mnuLoadReport3;
    private javax.swing.JMenuItem mnuLoadReport4;
    private javax.swing.JMenuItem mnuName;
    private javax.swing.JMenu mnuPrint;
    private javax.swing.JMenuItem mnuPrintReport;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JPanel pnlScrollPane;
    private javax.swing.JScrollPane scrReport;
    // End of variables declaration//GEN-END:variables

}
