package wildlog.ui.panel;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.border.LineBorder;
import org.jdesktop.application.Application;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.Element;
import wildlog.data.dataobjects.Location;
import wildlog.data.dataobjects.Sighting;
import wildlog.data.dataobjects.Visit;
import wildlog.data.enums.Certainty;
import wildlog.data.enums.ElementType;
import wildlog.ui.panel.interfaces.PanelNeedsRefreshWhenSightingAdded;

/**
 *
 * @author Delangeh
 */
public class PanelChecklist extends javax.swing.JPanel {
     // Variables:
    private WildLogApp app;
    private PanelNeedsRefreshWhenSightingAdded panelToRefresh;
    private Location location;
    private Visit visit;

    /** Creates new form PanelMoveVisit */
    public PanelChecklist(Location inLocation, Visit inVisit, PanelNeedsRefreshWhenSightingAdded inPanelToRefresh) {
        initComponents();
        app = (WildLogApp) Application.getInstance();
        loadElementList();
        location = inLocation;
        visit = inVisit;
        panelToRefresh = inPanelToRefresh;

        DefaultListModel sightedModel = new DefaultListModel();
        lstSightedCreatures.setModel(sightedModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFromCreatures = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSightedCreatures = new javax.swing.JList();
        btnConfirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chkElementType = new javax.swing.JCheckBox();
        cmbElementType = new javax.swing.JComboBox();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        dtpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 520));
        setMinimumSize(new java.awt.Dimension(750, 520));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wildlog.WildLogApp.class).getContext().getResourceMap(PanelChecklist.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstFromCreatures.setFont(resourceMap.getFont("lstFromCreatures.font")); // NOI18N
        lstFromCreatures.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstFromCreatures.setName("lstFromCreatures"); // NOI18N
        lstFromCreatures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFromCreaturesMouseClicked(evt);
            }
        });
        lstFromCreatures.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstFromCreaturesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstFromCreatures);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 340, 420));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lstSightedCreatures.setFont(resourceMap.getFont("lstSightedCreatures.font")); // NOI18N
        lstSightedCreatures.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstSightedCreatures.setName("lstSightedCreatures"); // NOI18N
        lstSightedCreatures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstSightedCreaturesMouseClicked(evt);
            }
        });
        lstSightedCreatures.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstSightedCreaturesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(lstSightedCreatures);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 350, 350));

        btnConfirm.setBackground(resourceMap.getColor("btnConfirm.background")); // NOI18N
        btnConfirm.setIcon(resourceMap.getIcon("btnConfirm.icon")); // NOI18N
        btnConfirm.setText(resourceMap.getString("btnConfirm.text")); // NOI18N
        btnConfirm.setToolTipText(resourceMap.getString("btnConfirm.toolTipText")); // NOI18N
        btnConfirm.setName("btnConfirm"); // NOI18N
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 140, 90));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        chkElementType.setText(resourceMap.getString("chkElementType.text")); // NOI18N
        chkElementType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkElementType.setName("chkElementType"); // NOI18N
        chkElementType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkElementTypeItemStateChanged(evt);
            }
        });
        chkElementType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkElementTypeActionPerformed(evt);
            }
        });
        add(chkElementType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmbElementType.setMaximumRowCount(9);
        cmbElementType.setModel(new DefaultComboBoxModel(ElementType.values()));
        cmbElementType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbElementType.setEnabled(false);
        cmbElementType.setName("cmbElementType"); // NOI18N
        cmbElementType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElementTypeActionPerformed(evt);
            }
        });
        add(cmbElementType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, -1));

        txtSearch.setText(resourceMap.getString("txtSearch.text")); // NOI18N
        txtSearch.setName("txtSearch"); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        btnSearch.setIcon(resourceMap.getIcon("btnSearch.icon")); // NOI18N
        btnSearch.setText(resourceMap.getString("btnSearch.text")); // NOI18N
        btnSearch.setToolTipText(resourceMap.getString("btnSearch.toolTipText")); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, -1));

        dtpDate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dtpDate.setFormats(new SimpleDateFormat("dd MMM yyyy"));
        dtpDate.setName("dtpDate"); // NOI18N
        add(dtpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 140, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 133, -1, -1));

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (dtpDate.getDate() != null) {
            dtpDate.setBorder(null);
            for (int t = 0; t < lstSightedCreatures.getModel().getSize(); t++) {
                String elementName = lstSightedCreatures.getModel().getElementAt(t).toString();
                Sighting tempSighting = new Sighting();
                tempSighting.setElementName(elementName);
                tempSighting.setLocationName(location.getName());
                tempSighting.setVisitName(visit.getName());
                tempSighting.setDate(dtpDate.getDate());
                tempSighting.setCertainty(Certainty.SURE);
                app.getDBI().createOrUpdate(tempSighting);
            }

            if (panelToRefresh != null) {
                panelToRefresh.refreshTableForSightings();
            }
            // Close the dialog - (Evt is null if the Image Upload calls save method...)
            if (evt != null) {
                JDialog dialog = (JDialog)getParent().getParent().getParent().getParent();
                dialog.dispose();
            }
        }
        else {
            dtpDate.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void lstFromCreaturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFromCreaturesMouseClicked
        if (evt == null || evt.getClickCount() == 2) {
            Element temp = (Element)lstFromCreatures.getSelectedValue();
            DefaultListModel model = (DefaultListModel)lstSightedCreatures.getModel();
            if (temp != null) {
                if (!model.contains(temp.toString())) {
                    model.addElement(temp.toString());
                }
            }
        }
    }//GEN-LAST:event_lstFromCreaturesMouseClicked

    private void lstSightedCreaturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstSightedCreaturesMouseClicked
        if (evt == null || evt.getClickCount() == 2) {
            if (lstSightedCreatures.getSelectedIndex() >= 0) {
                String temp = lstSightedCreatures.getSelectedValue().toString();
                DefaultListModel model = (DefaultListModel)lstSightedCreatures.getModel();
                if (model.contains(temp)) {
                    model.removeElement(temp);
                }
            }
        }
    }//GEN-LAST:event_lstSightedCreaturesMouseClicked

    private void chkElementTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkElementTypeItemStateChanged
        cmbElementType.setEnabled(chkElementType.isSelected());
    }//GEN-LAST:event_chkElementTypeItemStateChanged

    private void chkElementTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkElementTypeActionPerformed
        loadElementList();
    }//GEN-LAST:event_chkElementTypeActionPerformed

    private void cmbElementTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElementTypeActionPerformed
        loadElementList();
    }//GEN-LAST:event_cmbElementTypeActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSearchActionPerformed(null);
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadElementList();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lstFromCreaturesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstFromCreaturesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            lstFromCreaturesMouseClicked(null);
    }//GEN-LAST:event_lstFromCreaturesKeyPressed

    private void lstSightedCreaturesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstSightedCreaturesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            lstSightedCreaturesMouseClicked(null);
    }//GEN-LAST:event_lstSightedCreaturesKeyPressed


    // Private Methods
    private void loadElementList() {
        // Need to wrap in ArrayList because of java.lang.UnsupportedOperationException
        Element searchElement = new Element();
        if (chkElementType.isSelected())
            searchElement.setType((ElementType)cmbElementType.getSelectedItem());
        if (txtSearch.getText().length() > 0)
            searchElement.setPrimaryName(txtSearch.getText());
        List<Element> elements = new ArrayList<Element>(app.getDBI().list(searchElement));
        Collections.sort(elements);
        DefaultListModel fromModel = new DefaultListModel();
        for (Element tempElement : elements) {
            fromModel.addElement(tempElement);
        }
        lstFromCreatures.setModel(fromModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chkElementType;
    private javax.swing.JComboBox cmbElementType;
    private org.jdesktop.swingx.JXDatePicker dtpDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstFromCreatures;
    private javax.swing.JList lstSightedCreatures;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
