package wildlog.ui.panel;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import org.jdesktop.application.Application;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.Element;
import wildlog.data.dataobjects.Location;
import wildlog.utils.ui.Utils;


public class ReportingDialog extends JDialog {
    private WildLogApp app;
    private Location location;
    private Element element;

    public ReportingDialog(Frame inParent,
            Location inLocationToMap,
            Element inElementToMap) {
        super(inParent);
        // Set passed in values
        app = (WildLogApp) Application.getInstance();
        location = inLocationToMap;
        element = inElementToMap;

        // Auto generated code
        initComponents();

        // Determine what buttons to show
        if (location == null) {
            btnViewLocation.setVisible(false);
        }

        // Setup the escape key
        final JDialog thisHandler = (JDialog)this;
        ActionListener escListiner = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        thisHandler.dispose();
                    }
                };
        thisHandler.getRootPane().registerKeyboardAction(
                escListiner,
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);

        // Position the dialog
        Utils.setDialogToCenter(app.getMainFrame(), thisHandler);

        // Pack
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btnViewSingleSighting = new javax.swing.JButton();
        btnViewLocation = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wildlog.WildLogApp.class).getContext().getResourceMap(ReportingDialog.class);
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        btnViewSingleSighting.setIcon(resourceMap.getIcon("btnViewSightingsAndDistributionMap.icon")); // NOI18N
        btnViewSingleSighting.setText(resourceMap.getString("btnViewSingleSighting.text")); // NOI18N
        btnViewSingleSighting.setFocusPainted(false);
        btnViewSingleSighting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewSingleSighting.setIconTextGap(10);
        btnViewSingleSighting.setMaximumSize(new java.awt.Dimension(230, 35));
        btnViewSingleSighting.setMinimumSize(new java.awt.Dimension(230, 35));
        btnViewSingleSighting.setName("btnViewSingleSighting"); // NOI18N
        btnViewSingleSighting.setPreferredSize(new java.awt.Dimension(230, 35));
        getContentPane().add(btnViewSingleSighting);

        btnViewLocation.setIcon(resourceMap.getIcon("btnViewLocation.icon")); // NOI18N
        btnViewLocation.setText(resourceMap.getString("btnViewLocation.text")); // NOI18N
        btnViewLocation.setFocusPainted(false);
        btnViewLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewLocation.setIconTextGap(10);
        btnViewLocation.setMaximumSize(new java.awt.Dimension(230, 35));
        btnViewLocation.setMinimumSize(new java.awt.Dimension(230, 35));
        btnViewLocation.setName("btnViewLocation"); // NOI18N
        btnViewLocation.setPreferredSize(new java.awt.Dimension(230, 35));
        getContentPane().add(btnViewLocation);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewLocation;
    private javax.swing.JButton btnViewSingleSighting;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
