

import java.awt.Color;
import java.awt.EventQueue;
import java.io.File;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import wildlog.data.enums.system.WildLogDataType;
import wildlog.sync.azure.SyncAzure;
import wildlog.sync.azure.dataobjects.SyncBlobEntry;

public class BlobTest extends JFrame {
    private SyncAzure syncAzure = new SyncAzure(
            "DefaultEndpointsProtocol=https;AccountName=wildlogtest;AccountKey=HHpe/UN5isNNVth/tJ1+b9ZzIf0U9yL/rbnmzsp8Rjq1J2HQ+AKmm5VekWNbrLvueXjS3VojW7Ck9bJsRvtROA==;EndpointSuffix=core.windows.net", 
            "wildlogtest", "HHpe/UN5isNNVth/tJ1+b9ZzIf0U9yL/rbnmzsp8Rjq1J2HQ+AKmm5VekWNbrLvueXjS3VojW7Ck9bJsRvtROA==", 
            123L, 12);

    public BlobTest() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSyncListBlobsBatch = new javax.swing.JButton();
        btnSyncListParentsBatch = new javax.swing.JButton();
        btnSyncListChildrenBatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Azure Sync Tester");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Azure Blob Sync Tester");

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnDownload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDownload.setText("Download");
        btnDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSyncListBlobsBatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSyncListBlobsBatch.setText("Sync List (Blobs)");
        btnSyncListBlobsBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSyncListBlobsBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncListBlobsBatchActionPerformed(evt);
            }
        });

        btnSyncListParentsBatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSyncListParentsBatch.setText("Sync List (Parents)");
        btnSyncListParentsBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSyncListParentsBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncListParentsBatchActionPerformed(evt);
            }
        });

        btnSyncListChildrenBatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSyncListChildrenBatch.setText("Sync List (Children)");
        btnSyncListChildrenBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSyncListChildrenBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncListChildrenBatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                            .addComponent(btnSyncListBlobsBatch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSyncListParentsBatch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSyncListChildrenBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSyncListBlobsBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSyncListParentsBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSyncListChildrenBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        syncAzure.uploadFile(WildLogDataType.ELEMENT, new File("C:\\_temp\\mol.jpg").toPath(), 777L, 555L, 
                "2019:07:25 14:27:00", "-33° 45' 0.62\"", "26° 31' 46.68\"");
        System.out.println("UPLOADED");
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        syncAzure.downloadFile(WildLogDataType.ELEMENT, new File("C:\\_temp\\mol.jpg").toPath(), 777L, 555L);
        System.out.println("DOWNLOADED");
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        syncAzure.deleteFile(WildLogDataType.ELEMENT, Long.toString(123L) + "/" + Long.toString(777L) + "/" + Long.toString(55L) + ".jpg");
        System.out.println("DELETED");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSyncListBlobsBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncListBlobsBatchActionPerformed
        List<SyncBlobEntry> lstSyncBlobEntry = syncAzure.getSyncListFilesBatch(WildLogDataType.ELEMENT);
        System.out.println("SYNCLIST BLOBS BATCH: ");
        System.out.println(lstSyncBlobEntry.size());
        for (SyncBlobEntry entry : lstSyncBlobEntry) {
            System.out.println(entry);
        }
    }//GEN-LAST:event_btnSyncListBlobsBatchActionPerformed

    private void btnSyncListParentsBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncListParentsBatchActionPerformed
        List<SyncBlobEntry> lstSyncBlobEntry = syncAzure.getSyncListFileParentsBatch(WildLogDataType.ELEMENT);
        System.out.println("SYNCLIST PARENTS BATCH: ");
        System.out.println(lstSyncBlobEntry.size());
        for (SyncBlobEntry entry : lstSyncBlobEntry) {
            System.out.println(entry);
        }
    }//GEN-LAST:event_btnSyncListParentsBatchActionPerformed

    private void btnSyncListChildrenBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncListChildrenBatchActionPerformed
        List<SyncBlobEntry> lstSyncBlobEntry = syncAzure.getSyncListFileChildrenBatch(WildLogDataType.ELEMENT, 777L);
        System.out.println("SYNCLIST CHILDREN BATCH: ");
        System.out.println(lstSyncBlobEntry.size());
        for (SyncBlobEntry entry : lstSyncBlobEntry) {
            System.out.println(entry);
        }
    }//GEN-LAST:event_btnSyncListChildrenBatchActionPerformed

    public static void main(String args[]) {
        // Setup the application
        try {
            // Set native Look and Feel
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            // Removes the dotted border around controls which is not consistent with Windows
            UIManager.put("Button.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("ToggleButton.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("CheckBox.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("TabbedPane.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("RadioButton.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("Slider.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
            UIManager.put("ComboBox.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        // Launch the application
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlobTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSyncListBlobsBatch;
    private javax.swing.JButton btnSyncListChildrenBatch;
    private javax.swing.JButton btnSyncListParentsBatch;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
