package wildlog.ui.panels.inaturalist.dialogs;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.apache.logging.log4j.Level;
import wildlog.WildLogApp;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.helpers.WLOptionPane;
import wildlog.ui.utils.UtilsUI;


public class INatAuthTokenDialog extends JDialog {
    private static final String INAT_AUTH_URL = "https://www.inaturalist.org/oauth/authorize"
                    + "?client_id=33639c729ed7cfaa1d6d23411c94c6225b60a54b8c2c65bdea2d0baa07e629c0"
                    + "&redirect_uri=http%3A%2F%2Fwww.mywild.co.za%2Fwildlog%2FiNatAuthCode.php"
                    + "&response_type=code";
    private String originalTokenText;

    
    public INatAuthTokenDialog(JFrame inParent) {
        super(inParent);
        initComponents();
        originalTokenText = txtToken.getText();
        UtilsDialog.setDialogToCenter(inParent, this);
        UtilsDialog.addModalBackgroundPanel(inParent, this);
        UtilsUI.attachClipboardPopup(txtToken);
    }
    
    public INatAuthTokenDialog(JDialog inParent) {
        super(inParent);
        initComponents();
        originalTokenText = txtToken.getText();
        UtilsDialog.setDialogToCenter(inParent, this);
        UtilsDialog.addModalBackgroundPanel(inParent, this);
        UtilsUI.attachClipboardPopup(txtToken);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnOpenAuthLink = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnHelpStep1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("iNaturalist Authorization");
        setIconImage(new ImageIcon(WildLogApp.class.getResource("resources/icons/iNaturalist_small.png")).getImage());
        setMinimumSize(new java.awt.Dimension(650, 200));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(650, 250));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/iNaturalist.png"))); // NOI18N
        lblTitle.setText("iNaturalist Authorization");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Step 1");

        btnOpenAuthLink.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenAuthLink.setText("Get Authorization Token");
        btnOpenAuthLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenAuthLink.setFocusPainted(false);
        btnOpenAuthLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenAuthLinkActionPerformed(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/OK.png"))); // NOI18N
        btnOK.setToolTipText("Close the dialog and use the specified iNaturalist Token.");
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOK.setFocusPainted(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>WildLog requires an iNaturalist Authorization Token in order to interact with your iNaturalist account. \n<br/>\nPlease follow the steps below to aquire the Token:</html>");

        btnHelpStep1.setText("Show URL");
        btnHelpStep1.setToolTipText("Show the URL that will be used to authorizae WildLog on iNaturalist.");
        btnHelpStep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelpStep1.setFocusPainted(false);
        btnHelpStep1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnHelpStep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpStep1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Step 2");

        txtToken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtToken.setText("Paste the iNaturalist Autherization Token from the MyWild website in here...");
        txtToken.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTokenFocusGained(evt);
            }
        });

        jLabel4.setText("<html>TIP: You can store the generated Token in a safe place and reuse it again later, or simply generate a new Token next time you need to interact with iNaturalist.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpenAuthLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(btnHelpStep1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToken)))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenAuthLink, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelpStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (originalTokenText != null && txtToken.getText() != null 
                && !txtToken.getText().trim().isEmpty() 
                && !originalTokenText.equals(txtToken.getText())) {
            WildLogApp.setINaturalistToken(txtToken.getText().trim());
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnOpenAuthLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenAuthLinkActionPerformed
        try {
            Desktop.getDesktop().browse(URI.create(INAT_AUTH_URL));
        }
        catch (IOException ex) {
            WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
        }
    }//GEN-LAST:event_btnOpenAuthLinkActionPerformed

    private void btnHelpStep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpStep1ActionPerformed
        WLOptionPane.showMessageDialog(this, 
                INAT_AUTH_URL, 
                "iNaturalist Authorization URL", WLOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHelpStep1ActionPerformed

    private void txtTokenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTokenFocusGained
        txtToken.selectAll();
    }//GEN-LAST:event_txtTokenFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelpStep1;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOpenAuthLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
