package wildlog.ui.dialogs;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import netscape.javascript.JSException;
import org.apache.logging.log4j.Level;
import wildlog.WildLogApp;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.maps.implementations.PointMap;


public class FilterGPSDialog extends JDialog {
    private WebView webView;
    private double northEast_Latitude;
    private double northEast_Longitude;
    private double southWest_Latitude;
    private double southWest_Longitude;


    public FilterGPSDialog(JFrame inParent) {
        super(inParent);
        WildLogApp.LOGGER.log(Level.INFO, "[FilterGPSDialog]");
        initComponents();
        // Setup the escape key
        final FilterGPSDialog thisHandler = this;
        thisHandler.getRootPane().registerKeyboardAction(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Strangely enough this seems to work better in the JavFX thread than outside it...
                        Platform.runLater(new Runnable() {
                            @Override
                            public void run() {
                                thisHandler.setVisible(false);
                                thisHandler.dispose();
                            }
                        });
                    }
                },
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
        // Setup the default behavior (this is for JFrames)
        UtilsDialog.setDialogToCenter(inParent, thisHandler);
        UtilsDialog.addModalBackgroundPanel(inParent, thisHandler);
        // Setup the map
        JFXPanel jfxPanel = new JFXPanel();
        jfxPanel.setPreferredSize(pnlMap.getSize());
        pnlMap.add(jfxPanel, BorderLayout.CENTER);
        // Show the map
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                jfxPanel.setScene(new Scene(new VBox(new Label("Loading"))));
                jfxPanel.getScene().setRoot(createPointMapGoogle());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        pnlMap = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter GPS Points");
        setIconImage(new ImageIcon(WildLogApp.class.getResource("resources/icons/GPS.png")).getImage());
        setMinimumSize(new java.awt.Dimension(560, 340));
        setModal(true);
        setName("Form"); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/OK.png"))); // NOI18N
        btnSave.setToolTipText("Confirm the GPS values.");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        pnlMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMap.setName("pnlMap"); // NOI18N
        pnlMap.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Filter Observations by GPS coordinates:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("<html>Select the area you want to filter on by dragging the box to the desired position on the map, then press the OK button.</html>");
        jLabel5.setName("jLabel5"); // NOI18N

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/SelectClear.png"))); // NOI18N
        btnClear.setText("Clear Selection");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnClear)
                .addGap(15, 15, 15)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMap, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                // Need to get the coords from the JavaFX thread
                northEast_Latitude = getCoordinate("getNorthEast_Latitude()");
                northEast_Longitude = getCoordinate("getNorthEast_Longitude()");
                southWest_Latitude = getCoordinate("getSouthWest_Latitude()");
                southWest_Longitude = getCoordinate("getSouthWest_Longitude()");
                // We are done, dispose this dialog
                // Strangely enough this seems to work better in the JavFX thread than outside it...
                setVisible(false);
                dispose();
            }
        });
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        northEast_Latitude = 0.0;
        northEast_Longitude = 0.0;
        southWest_Latitude = 0.0;
        southWest_Longitude = 0.0;
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                // Strangely enough this seems to work better in the JavFX thread than outside it...
                setVisible(false);
                dispose();
            }
        });
    }//GEN-LAST:event_btnClearActionPerformed

    private double getCoordinate(String inFunctionName) {
        if (webView != null) {
            try {
                Object result = webView.getEngine().executeScript(inFunctionName);
                if (result instanceof Double) {
                    return (double) result;
                }
                else
                if (result instanceof Integer) {
                    return (double) ((int) result);
                }
            }
            catch (JSException ex) {
                // Ignore most of these errors which can happen when pressing the OK button before the page was fully loaded
                WildLogApp.LOGGER.log(Level.WARN, ex.toString(), ex);
            }
            catch (Exception ex) {
                WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
            }
        }
        return 0.0;
    }
    
    private WebView createPointMapGoogle() {
        webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        // Get the template file
        final char[] buffer = new char[4096];
        final StringBuilder builder = new StringBuilder(7500);
        try (Reader in = new BufferedReader(new InputStreamReader(PointMap.class.getResourceAsStream("resources/dragbox_google.html"), "UTF-8"))) {
            int length = 0;
            while (length >= 0) {
                length = in.read(buffer, 0, buffer.length);
                if (length > 0) {
                    builder.append(buffer, 0, length);
                }
            }
        }
        catch (IOException ex) {
            WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
        }
        String template = builder.toString();
        // Set the template
        webEngine.loadContent(template);
        return webView;
    }

    public double getNorthEast_Latitude() {
        return northEast_Latitude;
    }

    public double getNorthEast_Longitude() {
        return northEast_Longitude;
    }

    public double getSouthWest_Latitude() {
        return southWest_Latitude;
    }

    public double getSouthWest_Longitude() {
        return southWest_Longitude;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlMap;
    // End of variables declaration//GEN-END:variables
}
