package wildlog.ui.dialogs;

import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.Level;
import wildlog.WildLogApp;
import wildlog.data.dataobjects.WildLogUser;
import wildlog.data.enums.WildLogUserTypes;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.helpers.UtilsTableGenerator;
import wildlog.ui.helpers.WLOptionPane;


public class UserManagementDialog extends JDialog {
    private final WildLogApp app = WildLogApp.getApplication();

    public UserManagementDialog(JFrame inParent) {
        super(inParent, true);
        WildLogApp.LOGGER.log(Level.INFO, "[UserManagementDialog]");
        initComponents();
        // Setup the default behavior
        UtilsDialog.setDialogToCenter(inParent, this);
        UtilsDialog.addModalBackgroundPanel(inParent, this);
        UtilsDialog.addModalBackgroundPanel(this, null);
        // If this is the first time managing users, then show a warning and add the owner first
        if (app.getDBI().countUsers() < 2) {
            int result = WLOptionPane.showConfirmDialog(app.getMainFrame(),
                    "<html>This WildLog Workspace is currently accessable to everybody. "
                            + "<br>If Workspace User Management is enabled, then access to this Workspace will be restricted by means of a login screen."
                            + "<br><b>Continue to enable Workspace User Management?</b></html>",
                    "Enable Workspace User Management?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                UserCreateDialog dialog = new UserCreateDialog(inParent, true);
                dialog.setVisible(true);
            }
            else {
// FIXME: hierdie werk nie... die popup maak steeds oop...
                setVisible(false);
                dispose();
            }
        }
        // Load table data
        if (app.getDBI().countUsers() >= 2) {
            UtilsTableGenerator.setupUsersTable(app, tblUsers);
        }
        else {
// FIXME: hierdie werk nie... die popup maak steeds oop...
            setVisible(false);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Workspace User Management");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Workspace User Management");

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Add.gif"))); // NOI18N
        btnAddUser.setToolTipText("Add a new user to the Workspace.");
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.setEnabled(WildLogApp.WILDLOG_USER_TYPE != WildLogUserTypes.VOLUNTEER);
        btnAddUser.setFocusPainted(false);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Delete.gif"))); // NOI18N
        btnDeleteUser.setToolTipText("Delete the selected user from the Workspace.");
        btnDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteUser.setEnabled(WildLogApp.WILDLOG_USER_TYPE != WildLogUserTypes.VOLUNTEER);
        btnDeleteUser.setFocusPainted(false);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsers.setFocusable(false);
        tblUsers.setRowHeight(20);
        tblUsers.setSelectionBackground(new java.awt.Color(116, 171, 89));
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        UserCreateDialog dialog = new UserCreateDialog(this, false);
        dialog.setVisible(true);
        // Reload the table
        UtilsTableGenerator.setupUsersTable(app, tblUsers);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        if (tblUsers.getSelectedRowCount() > 0) {
            String usernameToDelete = (String) tblUsers.getModel().getValueAt(tblUsers.convertRowIndexToModel(tblUsers.getSelectedRow()), 0);
            // Validate
            WildLogUser userToDelete = app.getDBI().findUser(usernameToDelete, WildLogUser.class);
            if (WildLogUserTypes.WILDLOG_MASTER == userToDelete.getType()) {
                WLOptionPane.showMessageDialog(this.getParent(),
                        "The WildLog Master user can't be deleted.",
                        "Invalid User Type", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (WildLogApp.WILDLOG_USER_TYPE == WildLogUserTypes.ADMIN && userToDelete.getType() != WildLogUserTypes.VOLUNTEER) {
                WLOptionPane.showMessageDialog(this.getParent(),
                        "Admin users can only delete Volunteer users.",
                        "Invalid User Type", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // As daar geen Owners oor is nie, dan moet al die ander users ook delete word
            List<WildLogUser> lstOwners = app.getDBI().listUsers(WildLogUserTypes.OWNER, WildLogUser.class);
            if (lstOwners.size() == 1 && lstOwners.get(0).getUsername().equalsIgnoreCase(usernameToDelete)) {
                int result = WLOptionPane.showConfirmDialog(app.getMainFrame(),
                    "<html>This WildLog Workspace is currently only accessable by registered users. "
                            + "<br>If the last Workspace Owner is deleted, then all remaining users will also be deleted "
                            + "and access to this Workspace will be open to everybody (no login screen will be shown)."
                            + "<br><b>Continue to disable Workspace User Management?</b></html>",
                    "Disable Workspace User Management?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    List<WildLogUser> lstUsers = app.getDBI().listUsers(null, WildLogUser.class);
                    for (WildLogUser user : lstUsers) {
                        app.getDBI().deleteUser(user.getUsername());
                    }
                    setVisible(false);
                    dispose();
                }
            }
            else {
                int result = WLOptionPane.showConfirmDialog(app.getMainFrame(),
                        "Are you sure you want to delete the selected user?",
                        "Delete User", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    app.getDBI().deleteUser(usernameToDelete);
                }
            }
            // Reload the table
            UtilsTableGenerator.setupUsersTable(app, tblUsers);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
