package wildlog.ui.dialogs;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import org.apache.logging.log4j.Level;
import wildlog.WildLogApp;
import wildlog.ui.dialogs.utils.UtilsDialog;
import wildlog.ui.helpers.WLFileChooser;
import wildlog.ui.helpers.filters.WorkspaceFilter;
import wildlog.ui.utils.DummyTaskbarFrame;
import wildlog.utils.WildLogApplicationTypes;
import wildlog.utils.WildLogPaths;


public class WorkspacePickerDialog extends JDialog {
    private Path workspacePath = null;
    private boolean selectionMade = false;
    private long workspaceID = 0;
    private boolean triggerImmediateSync = false;

    public WorkspacePickerDialog() {
        super(new DummyTaskbarFrame("WildLog Workspace", 
                new ImageIcon(WildLogApp.class.getResource("resources/icons/WildLog Icon.gif")).getImage()));
        WildLogApp.LOGGER.log(Level.INFO, "[WorkspacePickerDialog]");
        initComponents();
        pack();
        setLocationRelativeTo(null);
        UtilsDialog.addModalBackgroundPanel(this, null);
        UtilsDialog.addEscapeKeyListener(this);
        // Luister ook op die editor vir wanneer mens iets tik
        cmbWorkspacePath.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent inEvent) {
                activeWorkspacePathChanged((String) cmbWorkspacePath.getEditor().getItem());
                if (inEvent.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnConfirmWorkspaceActionPerformed(null);
                    inEvent.consume();
                }
            }
        });
        // Lees die wildloghome file vir die lys van workspaces, en laai dit dan in die combobox
        setupWorkspaceList();
    }
    
    private void setupWorkspaceList() {
        // Try to read the settings file containing the wildloghome (active workspace)
        try {
            // If the file does not exist create it before attempting to read it
            if (!Files.exists(WildLogApp.getACTIVE_WILDLOG_SETTINGS_FOLDER().resolve("wildloghome"))) {
                writeWildLogHome();
            }
            // Read the wildloghome file
            populateWorkspaceComboBox(readAndConfigureWorkspacePathBasedOnWildLogHomeFile());
        }
        catch (IOException ex) {
            // Daar was 'n probleem om die wildloghome settings file te lees, probeer om 'n nuwe wildloghome file te maak
            WildLogApp.LOGGER.log(Level.ERROR, "Could not read the wildloghome file. Will try to create a new one...");
            WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
            writeWildLogHome();
            try {
                populateWorkspaceComboBox(readAndConfigureWorkspacePathBasedOnWildLogHomeFile());
            }
            catch (IOException ioex) {
                // As ek steeds nie 'n wildloghome file kan gelees kry nie vra die user vir 'n wildloghome om te gebruik
                WildLogApp.LOGGER.log(Level.ERROR, ioex.toString(), ioex);
                configureWorkspacePathBasedOnFileBrowser(null, true, null);
            }
        }
    }
    
    private void populateWorkspaceComboBox(List<Path> lstWorkspaces) {
        cmbWorkspacePath.setModel(new DefaultComboBoxModel<>());
        if (!lstWorkspaces.isEmpty()) {
            String selectedWorkspace = lstWorkspaces.get(0).toString().trim(); // will always be the first row
            Collections.sort(lstWorkspaces);
            for (Path worspace : lstWorkspaces) {
                String workpacePath = worspace.toAbsolutePath().normalize().toString().trim();
                if (!workpacePath.isEmpty()) {
                    cmbWorkspacePath.addItem(workpacePath);
                }
            }
            cmbWorkspacePath.setSelectedItem(selectedWorkspace);
        }
        else {
            cmbWorkspacePath.addItem(calculateInitialWorkspacePath().trim());
        }
        cmbWorkspacePath.addItem("");
        if (cmbWorkspacePath.getSelectedIndex() >= 0) {
            activeWorkspacePathChanged((String) cmbWorkspacePath.getSelectedItem());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWrapper = new javax.swing.JPanel();
        lblFeature = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbWorkspacePath = new javax.swing.JComboBox<>();
        btnBrowse = new javax.swing.JButton();
        btnConfirmWorkspace = new javax.swing.JButton();
        btnCloudSync = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WildLog Workspace");
        setIconImage(new ImageIcon(WildLogApp.class.getResource("resources/icons/WildLog Icon.gif")).getImage());
        setMinimumSize(new java.awt.Dimension(550, 265));
        setModal(true);

        pnlWrapper.setBackground(new java.awt.Color(59, 91, 59));

        lblFeature.setBackground(new java.awt.Color(7, 41, 7));
        lblFeature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/WildLog Feature 2.png"))); // NOI18N
        lblFeature.setOpaque(true);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(237, 247, 234));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("WildLog Workspace");

        cmbWorkspacePath.setBackground(new java.awt.Color(59, 91, 59));
        cmbWorkspacePath.setEditable(true);
        cmbWorkspacePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbWorkspacePath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbWorkspacePath.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWorkspacePathItemStateChanged(evt);
            }
        });

        btnBrowse.setBackground(new java.awt.Color(59, 91, 59));
        btnBrowse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowse.setMargin(new java.awt.Insets(2, 12, 2, 12));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnConfirmWorkspace.setBackground(new java.awt.Color(59, 91, 59));
        btnConfirmWorkspace.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnConfirmWorkspace.setText("OPEN / CREATE");
        btnConfirmWorkspace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmWorkspaceActionPerformed(evt);
            }
        });

        btnCloudSync.setBackground(new java.awt.Color(59, 91, 59));
        btnCloudSync.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCloudSync.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Sync.png"))); // NOI18N
        btnCloudSync.setText("Cloud Download");
        btnCloudSync.setToolTipText("Download a Workspace that was previously synced to the cloud.");
        btnCloudSync.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloudSync.setMargin(new java.awt.Insets(2, 6, 2, 6));
        btnCloudSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloudSyncActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(59, 91, 59));
        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wildlog/resources/icons/Delete_Small.gif"))); // NOI18N
        btnRemove.setText("Forget Workspace");
        btnRemove.setToolTipText("Remove the selected Workspace from the list. (Does not delete the Workspace, just removes it from the list.)");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.setMargin(new java.awt.Insets(2, 6, 2, 6));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWrapperLayout = new javax.swing.GroupLayout(pnlWrapper);
        pnlWrapper.setLayout(pnlWrapperLayout);
        pnlWrapperLayout.setHorizontalGroup(
            pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(pnlWrapperLayout.createSequentialGroup()
                        .addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCloudSync, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlWrapperLayout.createSequentialGroup()
                        .addComponent(cmbWorkspacePath, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrowse))
                    .addComponent(lblFeature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlWrapperLayout.setVerticalGroup(
            pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWrapperLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbWorkspacePath, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnConfirmWorkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlWrapperLayout.createSequentialGroup()
                        .addComponent(btnCloudSync, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmWorkspaceActionPerformed
        if (evt != null && btnCloudSync.isEnabled() && WildLogApp.WILDLOG_APPLICATION_TYPE == WildLogApplicationTypes.WILDLOG_WEI_REMOTE) {
            btnCloudSyncActionPerformed(evt);
            return;
        }
        if (workspacePath != null) {
            // Write the workspaces in the wildloghome file
            writeWildLogHome();
            // Set the active workspace prefix
            WildLogPaths.setWorkspacePrefix(workspacePath.toString());
            // Create the workspace folder (if needed)
            if (Files.notExists(WildLogPaths.getFullWorkspacePrefix())) {
                try {
                    Files.createDirectories(WildLogPaths.getFullWorkspacePrefix());
                }
                catch (IOException ex) {
                    WildLogApp.LOGGER.log(Level.ERROR, "Can't create new workspace folder!");
                    WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
                }
            }
            selectionMade = true;
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnConfirmWorkspaceActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        if (configureWorkspacePathBasedOnFileBrowser((DummyTaskbarFrame) getParent(), false, (String) cmbWorkspacePath.getEditor().getItem())) {
            String workspace = WildLogPaths.getFullWorkspacePrefix().toString();
            if (((DefaultComboBoxModel) cmbWorkspacePath.getModel()).getIndexOf(workspace) < 0) {
                cmbWorkspacePath.addItem(workspace);
            }
            cmbWorkspacePath.setSelectedItem(workspace);
            activeWorkspacePathChanged(workspace);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnCloudSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloudSyncActionPerformed
        // Get the workspace ID of the workspace to be synced
        WorkspaceListSyncDialog workspaceDialog = new WorkspaceListSyncDialog(this);
        workspaceDialog.setVisible(true);
        if (workspaceDialog.getWorkspaceID() > 0) {
            workspaceID = workspaceDialog.getWorkspaceID();
            triggerImmediateSync = true;
            btnConfirmWorkspaceActionPerformed(null);
        }
    }//GEN-LAST:event_btnCloudSyncActionPerformed

    private void cmbWorkspacePathItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWorkspacePathItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            activeWorkspacePathChanged((String) evt.getItem());
        }
    }//GEN-LAST:event_cmbWorkspacePathItemStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedIndex = cmbWorkspacePath.getSelectedIndex();
        if (selectedIndex >= 0) {
            cmbWorkspacePath.removeItem(cmbWorkspacePath.getSelectedItem());
        }
        else {
            cmbWorkspacePath.getEditor().setItem("");
        }
        selectedIndex--;
        if (selectedIndex < -1) {
            selectedIndex = -1;
        }
        cmbWorkspacePath.setSelectedIndex(selectedIndex);
        writeWildLogHome();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void activeWorkspacePathChanged(String inPath) {
        workspacePath = Path.of(inPath).toAbsolutePath().normalize();
        if (Files.notExists(workspacePath)) {
            if (WildLogApp.WILDLOG_APPLICATION_TYPE != WildLogApplicationTypes.WILDLOG_WEI_REMOTE) {
                btnConfirmWorkspace.setText("CREATE WORKSPACE");
                btnCloudSync.setEnabled(true);
            }
            else {
                btnConfirmWorkspace.setText("SYNC NEW WORKSPACE");
                btnCloudSync.setEnabled(true);
            }
        }
        else {
            if (Files.exists(workspacePath.resolve(WildLogPaths.WILDLOG_DATA.getRelativePath()))) {
                btnConfirmWorkspace.setText("OPEN WORKSPACE");
                btnCloudSync.setEnabled(false);
            }
            else {
                if (WildLogApp.WILDLOG_APPLICATION_TYPE != WildLogApplicationTypes.WILDLOG_WEI_REMOTE) {
                    btnConfirmWorkspace.setText("CREATE WORKSPACE");
                    btnCloudSync.setEnabled(true);
                }
                else {
                    btnConfirmWorkspace.setText("SYNC NEW WORKSPACE");
                    btnCloudSync.setEnabled(true);
                }
            }
        }
    }
    
    private void writeWildLogHome() {
        FileWriter writer = null;
        try {
            writer = new FileWriter(WildLogApp.getACTIVE_WILDLOG_SETTINGS_FOLDER().resolve("wildloghome").toFile());
            // Write the selected (active / default) workspace first
            if (workspacePath != null) {
                WildLogApp.LOGGER.log(Level.DEBUG, "Wildloghome: '" + workspacePath + "' (selected)");
                writer.write(workspacePath.toString() + System.lineSeparator());
            }
            // Write the rest of the know workspaces
            for (int t = 0; t < cmbWorkspacePath.getItemCount(); t++) {
                String workspace = (String) cmbWorkspacePath.getItemAt(t).trim();
                if (!workspace.isEmpty() && !workspace.equals(workspacePath.toString())) {
                    WildLogApp.LOGGER.log(Level.DEBUG, "Wildloghome: '" + workspace + "'");
                    writer.write(workspace + System.lineSeparator());
                }
            }
        }
        catch (IOException ex) {
            WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
        }
        finally {
            if (writer != null) {
                try {
                    writer.flush();
                    writer.close();
                }
                catch (IOException ioex) {
                    WildLogApp.LOGGER.log(Level.ERROR, ioex.toString(), ioex);
                }
            }
        }
    }

    private String calculateInitialWorkspacePath() {
        Path defaultWorkspacePath = new File(File.separator).toPath().resolve(WildLogPaths.DEFAULT_WORKSPACE_NAME.getRelativePath());
        String wildloghome = "";
        if (defaultWorkspacePath.toFile().canWrite()) {
            wildloghome = defaultWorkspacePath.toAbsolutePath().toString();
        }
        else {
            wildloghome = System.getProperty("user.home") + File.separatorChar + WildLogPaths.DEFAULT_WORKSPACE_NAME.getRelativePath();
        }
        return Paths.get(wildloghome).toAbsolutePath().normalize().toString();
    }
    
    /**
     * Read all the Workspace paths saved in the wildloghome file.
     * 
     * Note: This can be a folder path or even a network URL
     *       - C:\WildLogToets\WildLog
     *       - W:\
     *       - \\weimaster\WildLogDinokeng
     */
    private List<Path> readAndConfigureWorkspacePathBasedOnWildLogHomeFile() throws IOException {
        List<Path> lstWorkspacePaths = new ArrayList<>();
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(WildLogApp.getACTIVE_WILDLOG_SETTINGS_FOLDER().resolve("wildloghome").toFile()));
            // Get the first (default) workspace path
            String workspacePath = reader.readLine();
            WildLogPaths.setWorkspacePrefix(workspacePath);
            lstWorkspacePaths.add(WildLogPaths.getFullWorkspacePrefix());
            // Read the other workspace paths
            while ((workspacePath = reader.readLine()) != null) {
                lstWorkspacePaths.add(Paths.get(workspacePath).toAbsolutePath().normalize());
            }
        }
        // No catch: The error should be thrown if something goes wrong
        finally {
            if (reader != null) {
                try {
                    reader.close();
                }
                catch (IOException ex) {
                    WildLogApp.LOGGER.log(Level.ERROR, ex.toString(), ex);
                }
            }
        }
        return lstWorkspacePaths;
    }

    private static boolean configureWorkspacePathBasedOnFileBrowser(final JFrame inParent, boolean inTerminateIfNotSelected, String inStartFolder) {
        WLFileChooser fileChooser = new WLFileChooser(inStartFolder);
        fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
        fileChooser.setDialogTitle("Please select the WildLog Workspace to use.");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setFileFilter(new WorkspaceFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setMultiSelectionEnabled(false);
        int result = fileChooser.showOpenDialog(inParent);
        if (result == JFileChooser.APPROVE_OPTION && fileChooser.getSelectedFile() != null) {
            Path selectedPath;
            if (fileChooser.getSelectedFile().isDirectory()) {
                selectedPath = fileChooser.getSelectedFile().toPath();
            }
            else {
                selectedPath = fileChooser.getSelectedFile().getParentFile().toPath();
            }
            WildLogPaths.setWorkspacePrefix(selectedPath.toAbsolutePath().toString());
            return true;
        }
        else {
            if (inTerminateIfNotSelected) {
                WildLogApp.getApplication().exit();
            }
        }
        return false;
    }
    
    public boolean isSelectionMade() {
        return selectionMade;
    }

    public long getWorkspaceID() {
        return workspaceID;
    }

    public boolean isTriggerImmediateSync() {
        return triggerImmediateSync;
    }
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (!visible) {
            ((DummyTaskbarFrame) getParent()).dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCloudSync;
    private javax.swing.JButton btnConfirmWorkspace;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbWorkspacePath;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFeature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlWrapper;
    // End of variables declaration//GEN-END:variables
}
